### PR TITLE
Fix the date of saint Pedro Calungsod, martyr

### LINKED ISSUE #205: Fix celebration date of `saintPedroCalungsodMartyr` in `philippines.ts`
According to the [Wiki](https://en.wikipedia.org/wiki/General_Roman_Calendar#Philippines), `saintPedroCalungsodMartyr` is celebrated on 2 April. If, however, it falls on Sunday of Lent or within Holy Week, it should be moved to the preceding Saturday.

### PR DESCRIPTION
**Pull request by emagnier**
Resolves #205.

According to wikipedia:

- When April 2 falls within Holy Week or the Octave of Easter, his feast is transferred to the Saturday of the Fifth Week of Lent, the day after the Friday of Sorrows and before Palm Sunday. ([source](https://en.wikipedia.org/wiki/Pedro_Calungsod#Feast_day))

- 2 April (preceding Saturday if date falls on a Sunday of Lent or within Holy Week). ([source](https://en.wikipedia.org/wiki/General_Roman_Calendar#Philippines))

### CODE REVIEW

File: src/calendars/philippines.ts [hunk 1]
```diff
@@ -38,7 +39,18 @@ const dates = async (config: RomcalConfig): Promise<Array<LiturgicalDayInput>> =
...
       key: 'pedro_calungsod_martyr',
       rank: Ranks.MEMORIAL,
-      date: dayjs.utc(`${year}-4-2`),
+      date: ((year: number): dayjs.Dayjs => {
+        const date = dayjs.utc(`${year}-4-2`);
+        const palmSunday = Dates.palmSunday(year);
+        const divineMercySunday = Dates.divineMercySunday(year);
+        // When 2 April is prevented, because of a Sunday of lent taking precedence
+        // or when it falls within Holy Week or the Octave of Easter,
+        // his feast is transferred to the Saturday before Palm Sunday
```
Comment (tukusejssirs) [inline src/calendars/philippines.ts]:
```suggestion
        // When 2 April occurs with a Sunday of Lent or the Holy Week
        // or the Octave of Easter, the celebration is transferred
        // to Saturday before Palm Sunday.
```

Although I am not exactly sure if _preceding Saturday if date falls on a Sunday of Lent_ means _any_ Sunday of Lent or just Palm Sunday and Sunday of Divine Mercy.

**Review by tukusejssirs — DISMISSED** [review]

File: src/calendars/philippines.ts (hunk 1 above)
Comment (emagnier) [reply src/calendars/philippines.ts]:
```suggestion
        // When 2 April occurs with a Sunday of Lent or the Holy Week
        // or the Octave of Easter, the celebration is transferred
        // to the Saturday before Palm Sunday.
```

Thank you for your change suggestions. In the last line, I'll keep the _"the" Saturday_, because it's a well-defined day. 

> Although I am not exactly sure if preceding Saturday if date falls on a Sunday of Lent means any Sunday of Lent or just Palm Sunday and Sunday of Divine Mercy.

By reading different sources, in my understanding, when this memorial is prevented, it is moved to the Saturday before Palm Sunday. We will refine this rule if we can get more (official) details.

Comment (tukusejssirs) [reply src/calendars/philippines.ts]: Okay, LGTM. 😉

**Comment by emagnier** [comment]
Thanks. I updated the branch with the last suggestion, and need again your GitHub approval to do the merge.

**Review by tukusejssirs — APPROVED** [review]
