### PR TITLE
fix(pt-br): teresa of jesus

### LINKED ISSUE #870: pt-BR translation: Wrong translation
On oct,15 on pt-BR translation  is:
"id":string"teresa_of_jesus_of_avila_virgin"
"name":string"São João de Ávila, presbítero e doutor da Igreja"
Correct name is: 
"Santa Teresa de Jesus, virgem e doutora da Igreja"    (name on CNBB website)

In English file is OK.
"id":string"teresa_of_jesus_of_avila_virgin"
"name":string"Saint Teresa of Jesus, Virgin and Doctor of the Church"

### PR DESCRIPTION
**Pull request by TobiTenno**
## What is the purpose of this pull request?

updating translation of teresa of jesus

closes #870 

## Concept

Localization

## Example code

No change

- [x] By submitting this pull request, I confirm that I have read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).

### CODE REVIEW

File: rites/roman1969/src/locales/pt-br.ts [hunk 1]
```diff
@@ -497,7 +497,8 @@ export const locale: Locale = {
     sunday_of_the_word_of_god: '3º Domingo do Tempo Comum, ou Domingo da Palavra de Deus',
     sylvester_i_pope: 'São Silvestre I, papa',
     teresa_benedicta_of_the_cross_stein_virgin: 'Santa Teresa Benedita da Cruz, virgem e mártir',
-    teresa_of_jesus_of_avila_virgin: 'São João de Ávila, presbítero e doutor da Igreja',
+    // src: https://www.cnbb.org.br/liturgia-diaria/ 15-Oct-2025 (Retrieved 24-Jun-2025)
+    teresa_of_jesus_of_avila_virgin: 'Santa Teresa de Jesús (de Ávila), virgen y doctora de la Iglesia',
```
Comment (tukusejssirs) [inline rites/roman1969/src/locales/pt-br.ts]: You used a Spanish celebration nsme for some reason. Update it to this please:

```suggestion
    teresa_of_jesus_of_avila_virgin: 'Santa Teresa de Jesus, virgem e doutora da Igreja',
```

**Review by tukusejssirs — CHANGES_REQUESTED** [review]

**Review by tukusejssirs — APPROVED** [review]
