### PR TITLE
Fixes and refactoring of the calendar metadata computing

### LINKED ISSUE #288: Add tests for the calendar metadata
On each **liturgical day objects**, romcal now output a few contextual information about the day within the `calendar`: https://github.com/romcal/romcal/blob/dev/docs/data-output.md#json-structure. 

```
  // ...
  calendar: {
    totalWeeksInGregorianYear: 53,
    totalWeeksInLiturgicalYear: 52,
    weekOfGregorianYear: 1,
    weekOfLiturgicalYear: 5,
    weekOfSeason: 2,
    dayOfGregorianYear: 1,
    dayOfLiturgicalYear: 32,
    dayOfSeason: 8,
    dayOfWeek: 3,
    dayOfWeekCountInMonth: 1,
    startOfLiturgicalYear: '2019-12-01T00:00:00.000Z',
    endOfLiturgicalYear: '2020-11-28T00:00:00.000Z',
    easter: '2020-04-12T00:00:00.000Z',
  },
  // ...
```

However, there is actually no written tests about these new data, and I think it deserves it.

### PR DESCRIPTION
**Pull request by emagnier**
Fixes https://github.com/romcal/romcal/issues/288.

I knew while rewriting the romcal core codebase, that the calendar metadata is a tricky part, and not enough tested until now. And indeed I discovered a few bugs while testing more that part.

This PR contains a test of the calendar metadata, and a few bug fixes:
- Calendar metadata were not correctly computed on several liturgical days
- When a same liturgical day can occur twice in the same liturgical year (e.g. Andrew Apostle), the calendar metadata wasn't correct on the first occurrence of this liturgical day
- If the Baptism of the Lord is a Monday, the proper of time of the early ordinary time wasn't correctly computed: Mondays were shifted by a week.

### CODE REVIEW

File: lib/models/calendar.ts [hunk 1]
```diff
@@ -60,16 +62,34 @@ export class Calendar implements BaseCalendar {
...
+      (baseData?.seasons ?? def.seasons).includes(Seasons.OrdinaryTime) &&
+      date.getTime() >= this.#startOfLaterOrdinaryTime.getTime();
+
+    let dayOfSeason =
       baseData?.calendar.dayOfSeason ??
       def.calendarMetadata.dayOfSeason ??
-      (startOfSeason ? dateDifference(date, startOfSeason) + 2 : NaN);
+      (startOfSeason ? dateDifference(date, startOfSeason) + 1 : NaN);
+
+    // In later Ordinary Time, we need to subtract the days of Lent, Paschal Triduum and Easter Time,
```
Comment (tukusejssirs) [inline lib/models/calendar.ts]:
```suggestion
    // In late Ordinary Time, we need to subtract the days of Lent, Paschal Triduum and Easter Time,
```

File: lib/models/calendar.ts [hunk 2]
```diff
@@ -60,16 +62,34 @@ export class Calendar implements BaseCalendar {
...
+    if (isLaterOrdinaryTime) {
+      dayOfSeason = dayOfSeason - 96;
+    }
+
+    let weekOfSeason =
+      baseData?.calendar.weekOfSeason ??
+      def.calendarMetadata.weekOfSeason ??
+      (startOfSeason ? Math.ceil((dayOfSeason + startOfSeason.getDay()) / 7) : NaN);
+
+    // In later Ordinary Time, we need compute the week number from the remaining days of the liturgical year
```
Comment (tukusejssirs) [inline lib/models/calendar.ts]:
```suggestion
    // In late Ordinary Time, we need compute the week number from the remaining days of the liturgical year
```

File: lib/models/calendar.ts [hunk 3]
```diff
@@ -192,7 +211,11 @@ export class Calendar implements BaseCalendar {
           // the baseData must be null.
           const baseData: LiturgicalDay | null = isFromProperOfTime
             ? null
-            : builtData.byKeys[builtData.datesIndex[dateStr][0]];
+            : builtData.byKeys[builtData.datesIndex[dateStr][0]]
+                // Look up for the right LiturgicalDay item, according to its date.
+                // Note: 2 LiturgicalDay objects with the same date can occur within the same liturgical year,
```
Comment (tukusejssirs) [inline lib/models/calendar.ts]:
```suggestion
                // Note: Two LiturgicalDay objects with the same date can occur within the same liturgical year,
```

File: lib/models/calendar.ts [hunk 4]
```diff
@@ -192,7 +211,11 @@ export class Calendar implements BaseCalendar {
...
+                // for example, Saint Andrew Apostle (30 November), in 2012.
```
Comment (tukusejssirs) [inline lib/models/calendar.ts]: > When a same liturgical day can occur twice in the same liturgical year (e.g. Andrew Apostle), the calendar metadata wasn't correct on the first occurrence of this liturgical day

I am curious what do you mean by this quote from the PR description and by this example (L217).

AFAIK, St Andrew is celebrated as _feast_ in the GRC, therefore there cannot be other celebration on that day (unless approved by the Holy See).

Also, how/when/where can St Andrew be celebrated _twice_ in a liturgical year?

File: lib/models/calendar.ts [hunk 5]
```diff
@@ -288,7 +306,14 @@ export class Calendar implements BaseCalendar {
     Object.keys(builtData.datesIndex).forEach((dateStr) => {
       // Order the LiturgicalDays objects, following the precedence rules defined in the UNLY #49.
       const dates: LiturgicalDay[] = builtData.datesIndex[dateStr]
-        .map((key) => builtData.byKeys[key])
+        .reduce((acc, key) => {
+          // Look up for the right LiturgicalDay item, according to its date.
+          // Note: 2 LiturgicalDay objects with the same date can occur within the same liturgical year,
```
Comment (tukusejssirs) [inline lib/models/calendar.ts]:
```suggestion
          // Note: Two LiturgicalDay objects with the same date can occur within the same liturgical year,
```

File: lib/utils/dates.ts [hunk 6]
```diff
@@ -860,6 +861,10 @@ export class Dates {
             ? lateOrdinaryStartWeekCount + Math.floor(idx / 7) + 1
             : lateOrdinaryStartWeekCount + Math.floor(idx / 7);
 
+          // When the Baptism of the Lord is a Monday, it means that the Ordinary Time start a Tuesday.
```
Comment (tukusejssirs) [inline lib/utils/dates.ts]:
```suggestion
          // When the Baptism of the Lord observed on Monday, Ordinary Time starts on Tuesday.
```

File: tests/calendar-builder.test.ts [hunk 7]
```diff
@@ -204,6 +208,96 @@ describe('Testing calendar generation functions', () => {
     });
   });
 
+  describe('Testing calendar metadata', () => {
+    const testCalendarMetada = async (scope: CalendarScope) => {
```
Comment (tukusejssirs) [inline tests/calendar-builder.test.ts]: Is it intentional to name this variable `testCalendarMetada`? Didn’t you want to name it `testCalendarMetadata`? :wink:

**Review by tukusejssirs — CHANGES_REQUESTED** [review]
@emagnier, thanks for finding some time for romcal (again)! I cannot find any real deal breaker, just some typos or code comment improvements (plus a question). :wink:

File: lib/models/calendar.ts (hunk 2 above)
Comment (emagnier) [reply lib/models/calendar.ts]:
```suggestion
    // In late Ordinary Time, we need to compute the week number from the remaining days of the liturgical year
```

File: lib/models/calendar.ts (hunk 3 above)
Comment (emagnier) [reply lib/models/calendar.ts]:
```suggestion
                // Note: Two LiturgicalDay objects with the same key can occur within the same liturgical year,
```

File: lib/models/calendar.ts (hunk 4 above)
Comment (emagnier) [reply lib/models/calendar.ts]: Good catch. From _2 LiturgicalDay objects with the same **date**_, I wanted to say _...with the same **key**_.

For example, in 2012, the liturgical year starts the 27th November 2011, and ends the 1st December 2012. So within this liturgical year you have twice the 30th November (the day of the feast of St Andrew).
Internally, romcal is computing dates within a liturgical scope, but it has to manage the situation like St Andrew, when civil dates are overlapping.

File: lib/utils/dates.ts (hunk 6 above)
Comment (emagnier) [reply lib/utils/dates.ts]:
```suggestion
          // When the Baptism of the Lord is observed on Monday, Ordinary Time starts on Tuesday.
```

File: tests/calendar-builder.test.ts (hunk 7 above)
Comment (emagnier) [reply tests/calendar-builder.test.ts]: No, I forgot a syllable. Thanks!

File: lib/models/calendar.ts [hunk 8]
```diff
@@ -288,7 +306,14 @@ export class Calendar implements BaseCalendar {
     Object.keys(builtData.datesIndex).forEach((dateStr) => {
       // Order the LiturgicalDays objects, following the precedence rules defined in the UNLY #49.
       const dates: LiturgicalDay[] = builtData.datesIndex[dateStr]
-        .map((key) => builtData.byKeys[key])
+        .reduce((acc, key) => {
+          // Look up for the right LiturgicalDay item, according to its date.
+          // Note: Two LiturgicalDay objects with the same date can occur within the same liturgical year,
```
Comment (emagnier) [inline lib/models/calendar.ts]:
```suggestion
          // Note: Two LiturgicalDay objects with the same key can occur within the same liturgical year,
```

File: lib/models/calendar.ts (hunk 4 above)
Comment (tukusejssirs) [reply lib/models/calendar.ts]: I see. Then let’s be a bit more verbose in the code comment. You might want to change the date format (`30 November 2011` → `November 30, 2011`).

```suggestion
                // for example, Saint Andrew Apostle (30 November 2011 and 30 November 2012), in liturgical year 2012, which starts on 27 November 2011 and ends 1 December 2012.
```

File: lib/models/calendar.ts [hunk 9]
```diff
@@ -288,7 +306,14 @@ export class Calendar implements BaseCalendar {
     Object.keys(builtData.datesIndex).forEach((dateStr) => {
       // Order the LiturgicalDays objects, following the precedence rules defined in the UNLY #49.
       const dates: LiturgicalDay[] = builtData.datesIndex[dateStr]
-        .map((key) => builtData.byKeys[key])
+        .reduce((acc, key) => {
+          // Look up for the right LiturgicalDay item, according to its date.
+          // Note: Two LiturgicalDay objects with the same key can occur within the same liturgical year,
+          // for example, Saint Andrew Apostle (30 November), in 2012.
```
Comment (tukusejssirs) [inline lib/models/calendar.ts]:
```suggestion
          // for example, Saint Andrew Apostle (30 November 2011 and 30 November 2012), in liturgical year 2012, which starts on 27 November 2011 and ends 1 December 2012.
```

**Review by tukusejssirs — APPROVED** [review]
