### PR TITLE
fix: some l10n issues (fix #295)

### LINKED ISSUE #295: Fix some issues with l10n files
@emagnier, you made some l10n issues when creating `v3`. Nothing serious, but still. Nevertheless, I’ll fix some other l10n issues too when creating the PR for this issue.

I’d like to fix them, but need you to confirm some stuff. Do tell me if you have some special requirements.

Anyway, no need to comment on of this, @emagnier, just go through it and add freely comment the suggested changes. If you agree with the proposed change, you can skip them; otherwise tell me what you think. Thanks! :pray:

Sorry for writing such a long issue description, but I wanted to be thorough. :wink:

---

1. I have never seen `º` used in English, therefore I sugest to use ordinary numbers. Check if the suggestion below is correct.

```js
// Original
octave: '{{count}}º Day within the Octave of the Nativity of the Lord',

// Suggested
octave: '$t(ordinals:{{count}}, capitalize) Day within the Octave of the Nativity of the Lord',
```

2. I think that all keys in `names` should be sorted in all locales.

3. I think we should remove `seasons` object from `en-gb.ts`. I know, I introduced this change, but now I think the changes in the `seasons` object does not matter. Even more: I think that the English Roman Missal (ed. typ. tertia) published in 2011 united the differences between the US and the UK terminology.

4. I’ll add `ordinals` to `sk.ts` and update the strings in `seasons` which use ordinal numbers.

5. I’ll proof `sk.ts`, as I have already found an issue (`Druhú nedeľa po narodení Pána` should be `Druhá nedeľa po narodení Pána`).

6. I’ll add all added keys to all locales.

7. Add the [l10n rules](https://github.com/romcal/romcal/issues/175#issuecomment-673048460) which are used to create the l10n keys to the docs.

8. Update the titles:
- `founder`/`foundress`;
- `king`/`queen`;
- `emperor`/`empress`;
- `pilgrim`.

9. We agreed to name the l10n keys according to [these rules](https://github.com/romcal/romcal/issues/175#issuecomment-673048460), therefore there are some issues with the following keys you added:

a. Missing canonisation level in the key value and title in the key name.

```js
adelaide_of_burgundy: 'Adelaide of Burgundy, Empress',
```

b. Missing surname; he was `Adelphus`, not `Adolph`.

```js
adelphus_of_metz_bishop: 'Saint Adolph, Bishop',
```

c. Remove `the` before `Saints`. In all `All Saints` (even when we mean just all saint of a particular region), we (usually) mean all saints, even unknown, therefore from grammatical point of view, we should not use the definite article (`the`).

As for the dioceses, the `Diocese of Paris` and the `Diocese of Saint-Denis` are considered as proper names, therefore we should use capital `D` in `Diocese`.

Actually, Paris is an archdiocese, isn’t it? Should it be renamed to `Archdiocese`?

```js
all_the_saints_of_the_diocese_of_paris: 'All the Saints of the diocese of Paris',
all_the_saints_of_the_diocese_of_saint_denis: 'All the Saints of the diocese of Saint-Denis',
```

d. In English, we usually don’t use `First Bishop of`, not even `Bishop of`, therefore I suggest to change it to `Saint Amandus of Strasbourg, Bishop` (key: `amandus_of_strasbourg_bishop`).

Also I think that the patronages of dioceses should always include the full name of the diocese (e.g. `Patron of the Diocese of Paris`). If you agree, I’ll update the [rules](https://github.com/romcal/romcal/issues/175#issuecomment-673048460) accordingly.

Thirdly, should we state two patronages in one key (`Patron of the city` and `the Diocese of Saint-Denis`)? I have a similar patronage in one of the Slovak dioceses, but I was thinking rather to create two separate keys, one used in the diocesan calendar, the other in the calendar of the city/town. Tell me what do you think.

```js
amandus_first_bishop_of_strasbourg: 'Saint Amand, First Bishop of Strasbourg',
denis_of_paris_bishop_patron_of_the_diocese_of_paris: 'Saint Denis, Martyr, First bishop, Patron of the diocese',
denis_of_paris_bishop_patron_of_the_diocese_of_saint_denis: 'Saint Denis, Bishop and Martyr,Patron of the city and the diocese of Saint-Denis',
```

e. Missing surname; I have found that he was an abbot in a monastery around Clermont, maybe in the Vosges. Should we call him St Amarin of Clermont or rather St Amarin of Vosges?

```js
amarin_abbot: 'Saint Amarin, Abbot and Martyr',
```

f. Do you think that German `Strassburg` should be used instead of `Starsbourg`? I think we might use `Strassburg` because that might be be the name of the city at the time, but I still suggest to change it to Strasbourg.

```js
arbogast_of_strassburg_bishop: 'Saint Arbogast, Bishop',
arbogast_of_strassburg_bishop_patron_of_the_diocese_of_strasbourg: 'Saint Arbogast, Bishop, Patron of the diocese of Strasbourg',
```

g. Which Aurelia is this? According to the Wiki, both are celebrated on 15 October. You don’t even state the date of death in `fr.ts`. I think is is Aurelia of Strasbourg, because it is celebrated in `france.strasbourg.ts`.
- Aurelia of Strasbourg († 4th c.) https://en.wikipedia.org/wiki/Aurelia_of_Strasbourg
- Aurelia of Regensburg († 1027) https://en.wikipedia.org/wiki/Aurelia_of_Regensburg

```js
aurelia_virgin: 'Saint Aurelia, Virgin',
```

h. In English, `Martyrs` should be written with capital initial letter (i.e. in title case)

```js
blessed_martyrs_of_paris: 'Blessed martyrs of Paris',
```

i. Is there any reason you decided to use `Religious` title in English? I could not find a reference with `Religious` in English, only with `Virgin`. Even in Latin (MR2004), she is called a virgin.

```js
catherine_laboure_virgin: 'Saint Catherine Labouré, Religious',
```

j. I suggest to change the name to `Ceraunus` (https://en.wikipedia.org/wiki/Ceraunus).

```js
ceran_of_paris_bishop: 'Saint Céran of Paris, Bishop',
```

k. I suggest we should agree upon the naming of the celebrations of dedications of churches (incl cathedrals). I think we should specify the official church names (localised if necessary) with the place (city/town) where they are located, e.g. `Notre-Dame Cathedral in Paris` or `Cathedral of Saint Denis in Paris`. If you agree, I’ll change the following key values as well as update the [rules](https://github.com/romcal/romcal/issues/175#issuecomment-673048460).

Actually, should `Cathedral of Saint Denis in Paris` be rather called a basilica ([src](https://en.wikipedia.org/wiki/Basilica_of_Saint-Denis))?

```js
dedication_of_the_cathedral_of_paris: 'Dedication of the Cathedral of Paris',
dedication_of_the_cathedral_of_saint_denis: 'Dedication of the Cathedral of Saint-Denis',
dedication_of_the_cathedral_of_strasbourg: 'Dedication of the Cathedral of Strasbourg',
```

l. In the following keys, I’d rather use `Sunday of Divine Mercy` and `Sunday of the Word of God` as subtitles (not a feature yet) to `Second Sunday of Easter`/`Third Sunday in Ordinary Time` celebration names, where a subtitle is additional property in the `LiturgicalDay`. However, if you really want (at least in the interim) we might keep the subtitle in the celebration name, but I suggest to change `or` to `or Sunday`.

```js
divine_mercy_sunday: 'Second Sunday of Easter, or of Divine Mercy',
sunday_of_the_word_of_god: 'Third Sunday in Ordinary Time, or of the Word of God',
```

m. Change the name to `Eligius`.

```js
eloi_of_noyon_bishop: 'Saint Eloi, Bishop',
```

n. `Trèves` in French is `Trier` in English

```js
eucharius_of_treves_bishop: 'Saint Eucharius, Bishop',
```

o. Why did you use `Saint` twice (even in French)? In romcal `v1`, this usually meant that the two persons are celebrated separately (as two optional memorials). If it is not the case here, I suggest to change the key value to `Saints Eugenie and Attala, Virgins` (even in French).

Change `Attale` to `Attala` ([src](https://catholicsaints.info/saint-attala-of-strasbourg/)).

Also the key should be changed to `eugenie_of_alsace_and_attala_of_alsace` as per the [rules](https://github.com/romcal/romcal/issues/175#issuecomment-673048460).

```js
eugenie_and_attale_of_alsace: 'Saint Eugenie et Saint Attale, Virgin',
```

p. I think we should add `founder`/`foundress` to the list of titles (see point 9 below), therefore (as per the rules), we should append `_founder` to the key name.

```js
frederic_ozanam: 'Blessed Frederic Ozanam, Founder',
```

q. Add `_of_autun`.

```js
leodegar_bishop_and_martyr: 'Saint Leodegar, Bishop and Martyr',
```

r. Change `of` to `de` (`Saint Louise de Marillac, Religious`).

```js
louise_of_marillac: 'Saint Louise of Marillac, Religious',
```

s. I suggest to change the key name to `ludan_of_scotland_pilgrim`

```js
ludan_pilgrim: 'Saint Ludan, Pilgrim',
```

t. Change the name to `Marcellus`

```js
marcel_of_paris_bishop: 'Saint Marcel of Paris, Bishop',
```

u. According to the rules, key name structure of religious people should include besides their religious name also their surname, therefore we should add `Guyart`.

According to Wiki, the English name of this blessed is `Marie of the Incarnation`.

You used a opening quote (`‘`) instead of an apostrophe (`’`, which is the same character as the closing quote), so this needs to be fixed in `fr.ts` and `en.ts`.

```js
marie_de_incarnation_religious: 'Blessed Marie de l‘Incarnation, Religious',
```

v. According to the rules, key name structure of religious people should include besides their religious name also their surname, therefore we should add `Smet`.

Although I could not find a reference, we might want to change her English name to `Marie of the Providence` (as it is with `Marie of the Incarnation Guyart`).

```js
marie_de_la_providence_virgin: 'Blessed Marie de la Providence, Virgin',
```

w. Add `de_jesus` to the key name.

Change `virgin` to `religious` in the key name.

Add surname `Milleret` to the English key value.

Use `Foundress` title instead of `Founder` in the key value.

```js
marie_eugenie_milleret_virgin: 'Saint Marie-Eugénie de Jésus, Religious and Founder',
```

x. I presume that this person is same as [this](https://en.wikipedia.org/wiki/Sophie-Th%C3%A9r%C3%A8se_de_Soubiran_La_Louvi%C3%A8re), but there are two differences:
- `Marie-Thérèse` is changed to `Sophie-Thérèse` (first name); her religious name is `Marie of the Sacred Heart`;
- she died on 7 June 1893.

If my assumption is correct, consider using the name `Mary of the Sacred Heart de Soubiran`.

```js
marie_therese_de_soubiran_virgin: 'Blessed Marie-Thérèse de Soubiran, Virgin',
```

y. It should be `Our Lady, Refuge of Sinners`.

```js
mary_refuge_of_sinner: 'Holy Mary, Refuge of Sinner',  
```

z. In English, there is no space before semicolon.

Remove the first `_and` from the key name.

Replace `treves` with `trier` in the key name.

Replace `Valere` with `Valerius` in the key name.

Replace `Euchaire` with `Eucharius` in the key name.

Add `Bishops` title.

IMO we should use either `maternus_of_cologne_valerius_of_treves_and_eucharius_bishops` or `first_apostles_of_alsace` as the key name.

Change the key value to either `First Apostles of the Church of Alsace: Saints Maternus, Valerius and Eucharius, Bishops` or `Saints Maternus, Valerius and Eucharius, Bishops, the First Apostles of the Church of Alsace` or simply `Saints Maternus, Valerius and Eucharius, Bishops`.

```js
maternus_of_cologne_and_valerius_of_treves_and_eucharius_first_apostles_of_alsace: 'The first Apostles of the Church of Alsace : Saints Maternus, Valere and Euchaire',
```

aa. Change `Merry` to `Mederic` and `Droctovée` to `Droctoveus` respectively.

Remove redundant `Saint` (and change the first one to `Saints`).

Change the key name to `mederic_of_autun_and_droctoveus_of_autun_abbots`.

```js
merry_and_saint_droctovee_abbots: 'Saint Merry and Saint Droctovée, Abbots',
```

ab. Change `Modeste` to `Modest` and `André` to `Andrew`.

```js
modeste_andlauer_and_andre_bauer_martyrs: 'Saints Modeste Andlauer and André Bauer, Martyrs',
```

ac. Change `Modeste` to `Modest`.

```js
modeste_andlauer_martyr: 'Saint Modeste Andlauer, Martyr',
```

ad. Change `Morandus` to `Morand`.

```js
morandus_of_cluny_monk: 'Saint Morandus, Monk',
```

ae. Add `priest` to the key name.

Actually, in `france.paris.ts`, do they celebrated him only with `priest` title? He was a religious, a priest and a founder.

```js
nicholas_barre: 'Blessed Nicholas Barré, Priest',
```

af. Add `and ` before `Patroness`.

```js
odile_of_alsace_abbess_patroness_of_alsace: 'Saint Odile, Abbess, Patroness of Alsace',
```

ag. Change `Ouen` to `Audoin`. Add `_of_rouen` to the key name.

```js
ouen_bishop: 'Saint Ouen, Bishop',
```

ah. Append `_empress` to the key name

```js
richardis_of_swabi: 'Saint Richardis, Empress',
```

ai. Consider changing the key name to `thursday_of_the_lords_supper`.

Consider moving the key to the `seasons` object.

```js
thursday_of_the_lord_s_supper: 'Thursday of the Lord’s Supper',
```

aj. Change `pape` to `pope`.

Consider removing `and Martyr`, as he was not a martyr (even MR2004 states that he _faithfully guided the Roman Church for eight years_ after the martyrdom of St Callistus).

```js
urban_i_pape: 'Saint Urban I, Pope and Martyr',
```

ak. Replace `treves` with `trier` in the key name.

```js
valerius_of_treves_bishop: 'Saint Valerius, Bishop',
```

al. @emagnier, you added `Hermit` title; it is celebrated so in `france.strasbourg.ts`? It is also celebrated in [Germany](https://www.eucharistiefeier.de/lk/api/lko0000.html) as `Wendelin, Einsiedler im Saarland` (`Wendelin, Hermit in Saarland`) and [Wiki](https://en.wikipedia.org/wiki/Wendelin_of_Trier) states that he was a hermit, and only some legends say he was later consecrated abbot.

```js
wendelin_of_trier_abbot: 'Saint Wendelin, Hermit and Abbot',
```

### PR DESCRIPTION
**Pull request by tukusejssirs**
This PR fixes some issues in #295.

Bellow is a list of all changes I made in this PR.

---

#### List of changed key names

The following key names were changed in comparison with `dev` branch.

- `adelaide_of_burgundy` → `adelaide_of_burgundy_empress`;
- `adelphus_bishop` → `adelphus_of_metz_bishop`;
- `all_souls` → `commemoration_of_all_the_faithful_departed`;
- `all_the_saints_of_the_diocese_of_paris` → `all_saints_of_the_archdiocese_of_paris`;
- `all_the_saints_of_the_diocese_of_saint_denis` → `all_saints_of_the_diocese_of_saint_denis`;
- `alphonsus_liguori_bishop` → `alphonsus_mary_liguori_bishop`;
- `amandus_first_bishop_of_strasbourg` → `amandus_of_strasbourg_bishop`;
- `amarin_abbot` → `amarin_of_alsace_abbot`;
- `annunciation` → `annunciation_of_the_lord`;
- `arbogast_of_strassburg_bishop_patron_of_the_diocese_of_strasbourg` → `arbogast_of_strasbourg_bishop_patron_of_the_archdiocese_of_strasbourg`;
- `arbogast_of_strassburg_bishop` → `arbogast_of_strasbourg_bishop`;
- `ascension` → `ascension_of_the_lord`;
- `assumption` → `assumption_of_the_blessed_virgin_mary`;
- `aurelia_virgin` → `aurelia_of_strasbourg_virgin`;
- `catherine_laboure_virgin` → `catherine_zoe_laboure_virgin`;
- `ceran_of_paris_bishop` → `ceraunus_of_paris_bishop`;
- `charles_de_foucauld` → `charles_of_jesus_de_foucauld`;
- `christ_the_king_sunday` → `our_lord_jesus_christ_king_of_the_universe`;
- `christmas` → `nativity_of_the_lord`;
- `corpus_christi` → `most_holy_body_and_blood_of_christ`;
- `cyril_the_philosopher_monk_and_methodius_of_thessaloniki_bishop_copatrons_of_europe` → `cyril_constantine_the_philosopher_monk_and_methodius_michael_of_thessaloniki_bishop_copatrons_of_europe`;
- `cyril_the_philosopher_monk_and_methodius_of_thessaloniki_bishop_slavic_missionaries` → `cyril_constantine_the_philosopher_monk_and_methodius_michael_of_thessaloniki_bishop_slavic_missionaries`;
- `cyril_the_philosopher_monk_and_methodius_of_thessaloniki_bishop` → `cyril_constantine_the_philosopher_monk_and_methodius_michael_of_thessaloniki_bishop`;
- `dedication_of_the_cathedral_of_paris` → `dedication_of_the_notre_dame_de_paris_cathedral_paris_france`;
- `dedication_of_the_cathedral_of_saint_denis` → `dedication_of_the_cathedral_basilica_of_saint_denis_france`;
- `dedication_of_the_cathedral_of_strasbourg` → `dedication_of_the_cathedral_of_notre_dame_de_strasbourg_france`;
- `denis_of_paris_bishop_patron_of_the_diocese_of_paris` → `denis_of_paris_bishop_patron_of_the_archdiocese_of_paris`;
- `denis_of_paris_bishop_patron_of_the_diocese_of_saint_denis` → `denis_of_paris_bishop_patron_of_the_city_and_of_the_diocese_of_saint_denis`;
- `eloi_of_noyon_bishop` → `eligius_of_noyon_bishop`;
- `epiphany` → `epiphany_of_the_lord`;
- `eucharius_of_treves_bishop` → `eucharius_of_trier_bishop`;
- `eugenie_and_attale_of_alsace` → `eugenia_of_alsace_and_attala_of_alsace_virgins`;
- `frederic_ozanam` → `frederic_ozanam_founder`;
- `good_friday` → `friday_of_the_passion_of_the_lord`;
- `guardian_angels` → `holy_guardian_angels`;
- `holy_family` → `holy_family_of_jesus_mary_and_joseph`;
- `immaculate_conception_of_mary_patroness_of_the_philippines` → `immaculate_conception_of_the_blessed_virgin_mary_patroness_of_the_philippines`;
- `immaculate_conception_of_mary_patroness_of_the_usa` → `immaculate_conception_of_the_blessed_virgin_mary_patroness_of_the_usa`;
- `immaculate_conception_of_mary` → `immaculate_conception_of_the_blessed_virgin_mary`;
- `jean_georges_rehm_priest_and_martyr` → `thomas_jean_georges_rehm_priest`;
- `leodegar_bishop_and_martyr` → `leodegar_of_autun_bishop`;
- `louise_of_marillac` → `louise_de_marillac_religious`;
- `ludan_pilgrim` → `ludan_of_scotland_pilgrim`;
- `marcel_of_paris_bishop` → `marcellus_of_paris_bishop`;
- `marie_de_incarnation_religious` → `mary_of_the_incarnation_barbara_acarie_religious`;
- `marie_de_la_providence_virgin` → `mary_of_the_providence_eugenie_smet_virgin`;
- `marie_eugenie_milleret_virgin` → `marie_eugenie_of_jesus_milleret_de_brou_virgin`;
- `marie_of_the_incarnation_guyart_religious` → `mary_of_the_incarnation_marie_guyart_religious`;
- `marie_therese_de_soubiran_virgin` → `mary_of_the_sacred_heart_sophie_therese_de_soubiran_la_louviere_virgin`;
- `mary_refuge_of_sinner` and `our_lady_of_refuge` → `our_lady_refuge_of_sinners`;
- `maternus_of_cologne_and_valerius_of_treves_and_eucharius_first_apostles_of_alsace` → `maternus_of_cologne_valerius_of_trier_and_eucharius_of_trier_bishops`;
- `maximilian_kolbe_priest` → `maximilian_mary_raymund_kolbe_priest`;
- `merry_and_saint_droctovee_abbots` → `mederic_of_autun_and_droctoveus_of_autun_abbots`;
- `modeste_andlauer_and_andre_bauer_martyrs` → `modestus_andlauer_and_andrew_bauer_martyrs`;
- `modeste_andlauer_martyr` → `modestus_andlauer_martyr`;
- `nativity_of_mary` → `nativity_of_the_blessed_virgin_mary`;
- `nicholas_barre` → `nicholas_barre_priest`;
- `ouen_bishop` → `audoen_of_rouen_bishop`;
- `palm_sunday` → `palm_sunday_of_the_passion_of_the_lord`;
- `pius_of_pietrelcina_priest` → `pius_francesco_forgione_priest`;
- `presentation_of_mary` → `presentation_of_the_blessed_virgin_mary`;
- `queenship_of_mary` → `queenship_of_the_blessed_virgin_mary`;
- `richardis_of_swabi` → `richardis_of_swabia_empress`;
- `rosalie_rendu_virgin` → `rosalie_jeanne_marie_rendu_virgin`;
- `thursday_of_the_lord_s_supper` → `thursday_of_the_lords_supper`;
- `transfiguration` → `transfiguration_of_the_lord`;
- `trinity_sunday` → `most_holy_trinity`;
- `urban_i_pape` → `urban_i_pope`;
- `valerius_of_treves_bishop` → `valerius_of_trier_bishop`;
- `wendelin_of_trier_abbot` → `wendelin_of_trier_hermit`.

<details>
  <summary><b>List of changes</b></summary>

- [x] `adelaide_of_burgundy`: 'Saint Adelaide of Burgundy, Empress':
  - rename key to `adelaide_of_burgundy_empress`;
  - localise this key to all locales;
  - `en.ts`: `Saint` added;
- [x] `adelphus_bishop`: 'Saint Adelphus, Bishop':
  - rename key to `adelphus_of_metz_bishop`;
  - localise this key to all locales;
  - `en.ts`: fix his name;
- [x] `all_the_saints_of_the_diocese_of_paris`: 'All Saints of the diocese of Paris':
  - rename key to `all_saints_of_the_archdiocese_of_paris`;
  - localise this key to all locales;
  - `en.ts`: use capital initial letter in `Archdiocese`;
  - `fr.ts`: keep `diocèse`;
- [x] `all_the_saints_of_the_diocese_of_saint_denis`: 'All Saints of the Diocese of Saint-Denis':
  - rename key to `all_saints_of_the_diocese_of_saint_denis`;
  - `en.ts`: use capital initial letter in `Diocese`;
  - localise this key to all locales;
- [x] `amandus_first_bishop_of_strasbourg`: 'Saint Amandus of Strasbourg, Bishop':
  - rename key to `amandus_of_strasbourg_bishop`;
  - localise this key to all locales;
  - `france.strasbourg.ts`: remove `customLocaleKey` property:
    - reasoning: currently, there is no other particular calendar, in which he is celebrated besides `france.strasbourg.ts`, therefore we don’t need to differentiate between the ‘regular’ name and one with `the First Bishop of Strasbourg`;
- [x] `amarin_abbot`: 'Saint Amarin, Abbot and Martyr':
  - rename key to `amarin_of_alsace_abbot`;
  - localise this key to all locales;
- [x] `arbogast_of_strassburg_bishop`: 'Saint Arbogast, Bishop':
  - rename key to `arbogast_of_strasbourg_bishop`;
  - localise this key to all locales;
- [x] `arbogast_of_strassburg_bishop_patron_of_the_diocese_of_strasbourg`: 'Saint Arbogast, Bishop, Patron of the diocese of Strasbourg':
  - rename key to `arbogast_of_strasbourg_bishop_patron_of_the_archdiocese_of_strasbourg`;
  - localise this key to all locales;
  - `en.ts`: add `and` between the titles;
  - `fr.ts`: keep `diocèse`;
- [x] `aurelia_virgin`: 'Saint Aurelia, Virgin':
  - rename key to `aurelia_of_strasbourg_virgin`;
  - in all locales but `fr.ts`, append `of Strasbourg`;
  - localise this key to all locales;
  - `fr.ts`: append `(IVème s.)`;
- [x] `benedict_of_aniane_abbot`: 'Saint Benedict of Aniane, Abbot':
  - localise this key to all locales;
- [x] `blessed_martyrs_of_paris`: 'Blessed martyrs of Paris':
  - `en.ts`: change `martyrs` to `Martyrs`;
  - localise this key to all locales;
- [x] `brigid_of_kildare_virgin`: 'Saint Brigid, Abbess':
  - localise this key to all locales;
- [x] `brigid_of_kildare_virgin_copatroness_of_ireland`:
  - localise this key to all locales;
- [x] `carmelites_of_compiegne_virgins_and_martyrs`: 'Blessed Carmelites of Compiègne, Virgins and Martyrs':
  - localise this key to all locales;
- [x] `catherine_laboure_virgin`: 'Saint Catherine Labouré, Religious':
  - rename key to `catherine_zoe_laboure_virgin`;
  - `en.ts`: change `Religious` to `Virgin`;
  - localise this key to all locales;
- [x] `ceran_of_paris_bishop`: 'Saint Céran of Paris, Bishop':
  - rename key to `ceraunus_of_paris_bishop`;
  - `en.ts`: change `Céran` to `Ceraunus`;
- [x] `charles_de_foucauld`: 'Blessed Charles de Foucauld, Priest':
  - rename key to `charles_of_jesus_de_foucauld`;
  - localise this key to all locales;
- [x] `daniel_brottier_priest`: 'Blessed Daniel Brottier, Priest':
  - localise this key to all locales;
- [x] `dedication_of_the_cathedral_of_paris`: 'Dedication of the Cathedral of Paris':
  - rename key to `dedication_of_the_notre_dame_de_paris_cathedral_paris_france`;
  - localise this key to all locales;
- [x] `dedication_of_the_cathedral_of_saint_denis`: 'Dedication of the Cathedral of Saint-Denis':
  - rename key to `dedication_of_the_cathedral_basilica_of_saint_denis_france`;
  - localise this key to all locales;
- [x] `dedication_of_the_cathedral_of_strasbourg`: 'Dedication of the Cathedral of Strasbourg':
  - rename key to `dedication_of_the_cathedral_of_notre_dame_de_strasbourg_france`;
  - localise this key to all locales;
- [x] `denis_of_paris_bishop_and_companions_martyrs`:
  - localise this key to `pt-br`;
- [x] `denis_of_paris_bishop_patron_of_the_diocese_of_paris`: 'Saint Denis, Martyr, First bishop, Patron of the diocese':
  - rename key to `denis_of_paris_bishop_patron_of_the_archdiocese_of_paris`;
  - localise this key to all locales;
- [x] `denis_of_paris_bishop_patron_of_the_diocese_of_saint_denis`: 'Saint Denis, Bishop and Martyr,Patron of the city and the diocese of Saint-Denis':
  - rename key to `denis_of_paris_bishop_patron_of_the_city_and_of_the_diocese_of_saint_denis`;
  - localise this key to all locales;
- [x] `divine_mercy_sunday`: 'Second Sunday of Easter, or of Divine Mercy':
  - `en.ts`: change to `Second Sunday of Easter or Sunday of Divine Mercy`;
  - `la.ts`: `Dominica in octava Paschæ seu Dominica de Divina Misericordia`;
  - localise this key to all locales;
- [x] `eloi_of_noyon_bishop`: 'Saint Eloi, Bishop':
  - rename key to `eligius_of_noyon_bishop`;
  - `en.ts`: change to `Saint Eligius, Bishop`;
  - localise this key to all locales;
- [x] `eucharius_of_treves_bishop`: 'Saint Eucharius, Bishop':
  - rename key to `eucharius_of_trier_bishop`;
  - localise this key to all locales;
- [x] `eugenie_and_attale_of_alsace`: 'Saint Eugenie et Saint Attale, Virgin':
  - rename key to `eugenia_of_alsace_and_attala_of_alsace_virgins`;
  - `en.ts`: change to `Saints Eugenia and Attala, Virgins`;
  - localise this key to all locales;
  - `martyrology.ts` and `france.strasbourg.ts`: rename `eugenie_of_alsace_virgin` and `attale_of_alsace_virgin` to `eugenia_of_alsace_virgin` and `attala_of_alsace_virgin` respectively;
- [x] `florentius_of_strasbourg_bishop`: 'Saint Florentius, Bishop':
  - localise this key to all locales;
- [x] `frederic_ozanam`: 'Blessed Frederic Ozanam, Founder':
  - rename key to `frederic_ozanam_founder`;
  - `en.ts`: change to `Blessed Frédéric Ozanam, Founder`;
  - `fr.ts`: and `lib/catalog/martyrology.ts`: change `Ozonaman` to `Ozanam`;
  - localise this key to all locales;
- [x] `germain_of_paris_bishop`: 'Saint Germain of Paris, Bishop':
  - localise this key to all locales;
- [x] `innocent_v_pope`: 'Blessed Innocent V, Pope':
  - localise this key to all locales;
- [x] `isabelle_of_france_virgin`: 'Blessed Isabelle of France, Virgin':
  - localise this key to all locales;
- [x] `jean_georges_rehm_priest_and_martyr`: 'Blessed Jean-Georges Rehm, Priest and Martyr':
  - rename key to `thomas_jean_georges_rehm_priest`;
  - localise this key to all locales;
- [x] `landry_of_paris_bishop`: 'Saint Landry of Paris, Bishop':
  - localise this key to all locales;
- [x] `leodegar_bishop_and_martyr`: 'Saint Leodegar, Bishop and Martyr':
  - rename key to `leodegar_of_autun_bishop`;
  - localise this key to all locales;
- [x] `louise_of_marillac`: 'Saint Louise of Marillac, Religious':
  - rename key to `louise_de_marillac_religious`;
  - `en.ts` and `martyrology.ts`: change `of` to `de`;
  - localise this key to all locales;
- [x] `ludan_pilgrim`: 'Saint Ludan, Pilgrim':
  - rename key to `ludan_of_scotland_pilgrim`;
  - localise this key to all locales;
- [x] `madeleine_sophie_barat_virgin`: 'Saint Madeleine Sophie Barat, Virgin':
  - localise this key to all locales;
- [x] `marcel_of_paris_bishop`: 'Saint Marcel of Paris, Bishop':
  - rename key to `marcellus_of_paris_bishop`;
  - `en.ts`: change to `Saint Marcellus of Paris, Bishop`;
  - localise this key to all locales;
- [x] `marie_de_incarnation_religious`: 'Blessed Marie de l‘Incarnation, Religious':
  - rename key to `mary_of_the_incarnation_barbara_acarie_religious`;
  - `en.ts`: change to `Blessed Mary of the Incarnation Barbara Acarie, Religious`;
  - `martyrology.ts`: change `name` to `Mary of the Incarnation Barbara Acarie`;
  - `fr.ts`: fixe the apostrophe;
  - localise this key to all locales;
- [x] `marie_of_the_incarnation_guyart_religious`: 'Saint Marie of the Incarnation Marie Guyart, Religious':
  - rename key to `mary_of_the_incarnation_marie_guyart_religious`;
  - `en.ts`: change to `Saint Mary of the Incarnation Marie Guyart, Religious`;
  - `martyrology.ts`: change `name` to `Mary of the Incarnation Marie Guyart`;
  - localise this key to all locales;
- [x] `marie_de_la_providence_virgin`: 'Blessed Marie de la Providence, Virgin':
  - rename key to `mary_of_the_providence_eugenie_smet_virgin`;
  - `en.ts`: change to `Blessed Mary of the Providence Eugénie Smet, Virgin`;
  - localise this key to all locales;
- [x] `sunday_of_the_word_of_god`: 'Third Sunday in Ordinary Time, or of the Word of God':
  - `en.ts`: change to `Third Sunday in Ordinary Time, or Sunday of the Word of God`;
  - localise this key to all locales (update all locales with the same words as in `en.ts`);
- [x] `marie_eugenie_milleret_virgin`: 'Saint Marie-Eugénie de Jésus, Religious and Founder':
  - rename key to `marie_eugenie_of_jesus_milleret_de_brou_virgin`;
  - `en.ts`: change to `Saint Marie-Eugénie of Jesus Milleret de Brou, Virgin and Foundress`;
  - localise this key to all locales;
- [x] `marie_therese_de_soubiran_virgin`: 'Blessed Marie-Thérèse de Soubiran, Virgin':
  - rename key to `mary_of_the_sacred_heart_sophie_therese_de_soubiran_la_louviere_virgin`;
  - `en.ts`: change to `Blessed Mary Thérèse de Soubiran La Louvière, Virgin`;
  - `lib/martyrology.ts`: change `name` to `Mary Thérèse de Soubiran La Louvière`;
  - localise this key to all locales;
- [x] `mary_refuge_of_sinner`: 'Holy Mary, Refuge of Sinner' and `our_lady_of_refuge`: 'Our Lady of Refuge':
  - `martyrology.ts`: remove `holy_mary_refuge_of_sinner` in favour of `our_lady_refuge_of_sinners`;
  - rename key to `our_lady_refuge_of_sinners`;
  - `en.ts`: change to `Our Lady, Refuge of Sinners`;
  - localise this key to all locales;
- [x] `maternus_of_cologne_and_valerius_of_treves_and_eucharius_first_apostles_of_alsace`: 'The first Apostles of the Church of Alsace : Saints Maternus, Valere and Euchaire':
  - rename key to `maternus_of_cologne_valerius_of_trier_and_eucharius_of_trier_bishops`;
  - `fr.ts`: fixe the apostrophe;
  - `en.ts`: change to `Saints Maternus, Valerius and Eucharius, Bishops`;
  - localise this key to all locales;
- [x] `maternus_of_cologne_bishop`: 'Saint Maternus, Bishop':
  - localise this key to all locales;
  - `lib/martyrology.ts`: change `name` to `Maternus`;
- [x] `merry_and_saint_droctovee_abbots`: 'Saint Merry and Saint Droctovée, Abbots':
  - rename key to `mederic_of_autun_and_droctoveus_of_autun_abbots`;
  - `en.ts`: change to `Saints Mederic and Droctoveus, Abbots`;
  - `lib/martyrology.ts`:
    - change `merry_abbot` to `mederic_of_autun_abbot` and `name` to `Mederic`;
    - change `droctovee_abbot` to `droctoveus_of_autun_abbot` and `name` to `Droctoveus`;
  - localise this key to all locales;
- [x] `modeste_andlauer_and_andre_bauer_martyrs`: 'Saints Modeste Andlauer and André Bauer, Martyrs':
  - rename key to `modestus_andlauer_and_andrew_bauer_martyrs`;
  - `en.ts`: change to `Saints Modestus Andlauer and Andrew Bauer, Martyrs`;
  - `lib/martyrology.ts`:
    - change `modeste_andlauer_martyr` to `modestus_andlauer_martyr` and `name` to `Modestus Andlauer`;
    - change `andre_bauer_martyr` to `andrew_bauer_martyr` and `name` to `Andrew Bauer`;
  - localise this key to all locales;
- [x] `modeste_andlauer_martyr`: 'Saint Modeste Andlauer, Martyr':
  - rename key to `modestus_andlauer_martyr`;
  - `en.ts`: change to `Saint Modestus Andlauer, Martyr`;
  - localise this key to all locales;
- [x] `morandus_of_cluny_monk`: 'Saint Morandus, Monk':
  - rename key to `morand_of_cluny_monk`;
  - `en.ts`: change to `Saint Morand, Monk`;
  - `lib/martyrology.ts`: change `name` to `Morand`;
  - localise this key to all locales;
- [x] `nicholas_barre`: 'Blessed Nicholas Barré, Priest':
  - rename key to `nicholas_barre_priest`;
  - localise this key to all locales;
- [x] `ouen_bishop`: 'Saint Ouen, Bishop':
  - rename key to `audoen_of_rouen_bishop`;
  - `en.ts`: change to `Saint Audoen, Bishop`;
  - `lib/martyrology.ts`: change `name` to `Audoen`;
  - localise this key to all locales;
- [x] `our_lady_of_the_miraculous_medal`: 'Our Lady of the Miraculous Medal':
  - localise this key to all locales;
- [x] `richardis_of_swabi`: 'Saint Richardis, Empress':
  - rename key to `richardis_of_swabia_empress`;
  - localise this key to all locales;
- [x] `rosalie_rendu_virgin`: 'Blessed Rosalie Rendu, Virgin':
  - rename key to `rosalie_jeanne_marie_rendu_virgin`;
  - localise this key to all locales;
- [x] `thursday_of_the_lord_s_supper`: 'Thursday of the Lord’s Supper':
  - rename key to `thursday_of_the_lords_supper`;
- [x] `translation_of_the_relics_of_odile_of_alsace_abbess`: 'Translation of the Relics of Saint Odile':
  - localise this key to all locales;
- [x] `odile_of_alsace_abbess`: 'Saint Odile of Alsace, Abbess':
  - `en.ts`: change to `Saint Odile, Abbess`;
  - localise this key to all locales;
- [x] `odile_of_alsace_abbess_patroness_of_alsace`: 'Saint Odile, Abbess, Patroness of Alsace':
  - localise this key to all locales;
- [x] `urban_i_pape`: 'Saint Urban I, Pope and Martyr':
  - rename key to `urban_i_pope`;
  - `en.ts`, `fr.ts`: remove `martyr`:
    - he was not a martyr (even MR2004 states that he _faithfully guided the Roman Church for eight years_ after the martyrdom of St Callistus);
    - both French _Lectionnaire propre pour le Diocèse de Strasbourg_ (2014) and French _Missel propre pour le Diocèse de Strasbourg_ (2017) use only `Pope` title;
  - localise this key to all locales;
- [x] `valerius_of_treves_bishop`: 'Saint Valerius, Bishop':
  - rename key to `valerius_of_trier_bishop`;
  - `lib/martyrology.ts`: change `name` to `Valerius of Trier`;
  - localise this key to all locales;
- [x] `wendelin_of_trier_abbot`: 'Saint Wendelin, Hermit and Abbot':
  - rename key to `wendelin_of_trier_hermit`;
  - `en.ts`, `fr.ts`: remove `Abbot`:
    - both French _Lectionnaire propre pour le Diocèse de Strasbourg_ (2014) and French _Missel propre pour le Diocèse de Strasbourg_ (2017) use only `Hermit` title;
    - [German calendar](https://www.eucharistiefeier.de/lk/api.php?jahr=2022&info=dtrfl&bahn=j&format=html&mg=14) seems to use only `Hermit` (look for _Wendelin, Einsiedler im Saarland_);
  - `cs.ts`, `la.ts`, `sk.ts`: replace `Abbot` with `Hermit`;
  - `la.ts`: replace `Wendelini` with `Vendelini`;
  - `lib/martyrology.ts`: change `name` to `Wendelin of Trier`;
  - localise this key to all locales;
- [x] `maximilian_kolbe_priest`: 'Saint Maximilian Kolbe, Priest and Martyr':
  - rename key to `maximilian_mary_raymund_kolbe_priest`;
  - `lib/martyrology.ts`: change `name` to `Maximilian Mary Kolbe`;
  - `en.ts`: change to `Saint Maximilian Mary Kolbe, Priest and Martyr`;
- [x] `pius_of_pietrelcina_priest`: 'Saint Pius of Pietrelcina, Priest':
  - rename key to `pius_francesco_forgione_priest`;
  - localise this key to all locales;
- [x] append `_of_the_lord` to the following key names, as well as their `name` in `lib/catalog/martyrology.ts`:
  - `annunciation`;
  - `ascension`;
  - `transfiguration`;
  - `epiphany`;
- [x] `pt-br.ts`: localise `all_souls`;
- [x] rename `all_souls` to `commemoration_of_all_the_faithful_departed`;
- [x] `alphonsus_liguori_bishop`: 'Saint Alphonsus Liguori, Bishop and Doctor of the Church':
  - rename key to `alphonsus_mary_liguori_bishop`;
  - `en.ts`: change to `Saint Alphonsus Mary Liguori, Bishop and Doctor of the Church`;
  - localise this key to all locales;
- [x] `good_friday`: 'Good Friday':
  - rename key to `friday_of_the_passion_of_the_lord`;
  - `lib/martyrology.ts`: change `name` to `Friday of the Passion of the Lord`;
  - `en.ts`: change to `Friday of the Passion of the Lord`;
- [x] rename `assumption` to `assumption_of_the_blessed_virgin_mary`;
- [x] rename `christ_the_king_sunday` to `our_lord_jesus_christ_king_of_the_universe`;
- [x] rename `corpus_christi` to `most_holy_body_and_blood_of_christ`;
- [x] rename `palm_sunday` to `palm_sunday_of_the_passion_of_the_lord`;
- [x] rename `guardian_angels` to `holy_guardian_angels`;
- [x] rename `holy_family` to `holy_family_of_jesus_mary_and_joseph`;
- [x] rename `immaculate_conception_of_mary`, `immaculate_conception_of_mary_patroness_of_the_philippines`, `immaculate_conception_of_mary_patroness_of_the_usa` to `immaculate_conception_of_the_blessed_virgin_mary*`;
- [x] rename `nativity_of_mary` to `nativity_of_the_blessed_virgin_mary`;
- [x] rename `presentation_of_mary` to `presentation_of_the_blessed_virgin_mary`;
- [x] rename `queenship_of_mary` to `queenship_of_the_blessed_virgin_mary`;
- [x] rename `trinity_sunday` to `most_holy_trinity`;
- [x] `lib/catalog/martyrology.ts`: rename `the_saints_of_lindisfarne` to `saints_of_lindisfarne` and its name to `The Saints of Lindisfarne`;
- [x] `en.ts`: use English celebration names from `mr_en_2011` (ed. typ. tertia):
  - [x] add initial `The` to some celebrations in l10n files and `name` in `lib/catalog/martyrology.ts`:
    - `all_souls`;
    - `annunciation`;
    - `ascension`;
    - `assumption`;
    - `baptism_of_the_lord`;
    - `chair_of_saint_peter_the_apostle`;
    - `conversion_of_saint_paul_the_apostle`;
    - `corpus_christi`;
    - `dedication_of_the_basilica_of_saint_mary_major`;
    - `dedication_of_the_basilicas_of_saints_peter_and_paul_apostles`;
    - `dedication_of_the_cathedral_basilica_of_saint_denis_france`;
    - `dedication_of_the_cathedral_of_notre_dame_de_strasbourg_france`;
    - `dedication_of_the_lateran_basilica`;
    - `dedication_of_the_notre_dame_de_paris_cathedral_paris_france`;
    - `epiphany`;
    - `exaltation_of_the_holy_cross`;
    - `first_martyrs_of_the_holy_roman_church`;
    - `guardian_angel_of_portugal`;
    - `guardian_angels`;
    - `holy_child_of_cebu`;
    - `holy_family`;
    - `holy_innocents_martyrs`;
    - `immaculate_conception_of_mary_patroness_of_the_philippines`;
    - `immaculate_conception_of_mary_patroness_of_the_usa`;
    - `immaculate_conception_of_mary`;
    - `immaculate_heart_of_mary`;
    - `most_holy_name_of_jesus`;
    - `most_holy_name_of_mary`;
    - `most_sacred_heart_of_jesus`;
    - `nativity_of_john_the_baptist`;
    - `nativity_of_mary`;
    - `passion_of_saint_john_the_baptist`;
    - `presentation_of_mary`;
    - `presentation_of_the_lord`;
    - `queenship_of_mary`;
    - `seven_holy_founders_of_the_servite_order`;
    - `transfiguration`;
    - `trinity_sunday`;
    - `visitation_of_mary`;
  - [x] change `dedication_of_consecrated_churches` value to `The Dedication of Consecrated Churches Whose Date of Consecration is Unknown`;
  - [x] `john_mary_vianney_priest`: add `Mary`;
  - [x] `therese_of_the_child_jesus_and_the_holy_face_of_lisieux_virgin` and `therese_of_the_child_jesus_and_the_holy_face_of_lisieux_virgin_copatroness_of_france`: remove `and the Holy Face of Lisieux`;
  - [x] `teresa_of_jesus_of_avila_virgin`: remove `of Ávila`;
  - [x] `miguel_agustin_pro_priest`: replace `Agustin` with `Agustín`;
  - [x] use comma before patronage titles (like in `la` and `sk`);
  - [x] `christmas`:
    - [x] change the key name to `nativity_of_the_lord`;
    - [x] change the value to `The Nativity of the Lord (Christmas)`;
- [x] `en-gb.ts`: remove following keys:
  - `corpus_christi`;
  - `holy_thursday`;
  - `seven_holy_founders_of_the_servite_order`;
- [x] `la.ts`: use Latin celebration names from `mr_la_2008` (ed. typ. tertia, reimpressio emendata);
- [x] `la.ts` and `sk.ts`, based on _Missale Romanum_ (ed. typ. tertia, Slovak and Latin):
  - [x] add a comma between personal title and the following `et`/`a` (and) conjunction;
  - [x] separate all patronage titles from the regular titles using a comma and no `et`/`a` (and) conjunction is removed from multiple regular conjunctions;
- [x] `slovakia.ts` and `europe.ts`: remove `martyrology: ['cyril_constantine_the_philosopher_monk', 'methodius_michael_of_thessaloniki_bishop']` from `cyril_constantine_the_philosopher_monk_and_methodius_michael_of_thessaloniki_bishop`, as this is already inherited from `proper-of-saints.ts` (GRC);
- [x] `es.ts`: fix some issues raised by @CodingAleCR:
  - use `Doctora` (one female `Doctor`) for female doctors of the Church;
  - change `immaculate_conception_of_mary` to `Inmaculada Concepción de María`;
- [x] `cs.ts`:
  - [x] fix casing of `Srdce` in `most_sacred_heart_of_jesus` (see also igneus/calendarium-romanum#93);
  - [x] translate `Bishop` title in `muredach_of_killala_bishop`;
  - [x] localise forgotten parts of `columba_of_iona_abbot_copatron_of_ireland`;
- [x] `fr.ts`:
  - [x] replace `✝` (`U+271D`) with `†` (`U+2020`);
  - [x] add missing `†` before death dates;
  - [x] replace `siècle` with `s.`;
  - [x] put death dates always in brackets;
  - [x] `sunday_of_the_word_of_god`: add `Dimanche` after `ou` word, i.e. `Troisième dimanche du Temps Ordinaire, ou Dimanche de la Parole de Dieu`;
- [x] `la.ts`:
  - update the value of the following keys based on `rm_la_2008`:
    - `john_de_brebeuf_isaac_jogues_priests_and_companions_martyrs` → `Ss. Ioannis de Brébeuf et Isaac Jogues, presbyterorum, et sociorum, martyrum`;
    - `john_de_brebeuf_isaac_jogues_priests_and_companions_martyrs_copatrons_of_canada` → `Ss. Ioannis de Brébeuf et Isaac Jogues, presbyterorum, et sociorum, martyrum, patronorum secundariorum Canadæ`;
    - `mary_mother_of_god` → `In octava Nativitatis. Sollemnitas Sanctæ Dei Genetricis Mariæ`;
    - `seven_holy_founders_of_the_servite_order` → `Ss. septem Fundatorum Ordinis Servorum B. M. V.`;
    - `joseph_the_worker` → `S. Iosephi opificis`;
    - `passion_of_saint_john_the_baptist` → `In Passione S. Ioannis Baptistæ`;
    - `wenceslaus_i_of_bohemia_martyr` → `S. venceslai, martyris`;
    - `wenceslaus_i_of_bohemia_martyr_patron_of_the_czech_nation` → `S. Venceslai, martyris et patroni de gente Bohemica`;
    - `teresa_of_jesus_of_avila_virgin` → `S. Teresiæ a Iesu, virginis et Ecclesiæ doctoris`;
    - `dedication_of_the_lateran_basilica` → `In Dedicatione Basilicæ Lateranensis`;
  - fix some typos:
    - `david_of_wales_bishop_patron_of_wales`: `episcopis` → `episcopi`;
    - `david_of_wales_bishop`: `episcopis` → `episcopi`;
    - `finding_of_the_holy_cross`: `Sanctae` → `Sanctæ`;
    - `laurence_wang_bing_and_companions_martyrs`: remove comma before `et`;
    - `martin_wu_xuesheng_and_companions_martyrs`: remove comma before `et`;
    - `teresa_of_portugal_religious`: `religiosae` → `religiosæ`;
    - `therese_of_the_child_jesus_and_the_holy_face_of_lisieux_virgin_copatroness_of_france`: `Ecclesiæ doctori` → `Ecclesiæ doctoris`;
- [x] `pl.ts`: fix some typos:
  - `pontian_i_pope_and_hippolytus_of_rome_priest`: `prezbiteras` → `prezbitera`;
  - `peter_sanz_bishop`: use titles in lowercase;
- [x] rename `cyril_the_philosopher_monk_and_methodius_of_thessaloniki_bishop*` keys to `cyril_the_philosopher_monk_and_methodius_of_thessaloniki_bishop*`:
- [x] `en.ts`: change the value of `dedication_of_consecrated_churches` to `Dedication of consecrated churches whose date of consecration is unknown'`;
- [x] `sk.ts`: localise `cycles` and `ordinals`:
  - `ordinals` are localised only partially, as we need to localise at least Nominative and Genitive for all three genders of all numbers, which seems to me easier using `i18next-fluent`;
- [x] `ireland.ts`: remove `pius_francesco_forgione_priest`, as it is already defined in the GRC;
- [x] additional changes in `sk.ts` based on `mr_sk_2021`:
  - remove `spolu-` (Slovak equivalent of English `co-`) from key values, i.e. there is no `copatron(ness)` nor `secondary patron` in key values in `sk.ts`;
  - add `preblahoslavenej` (roughly `blessed` in BVM / Our Lady) to all celebrations mentioning Our Lady unless `mr_sk_2021` explicitly uses a celebration name without it;
  - change `rehoľnice` (one female `religious`) to `rehoľníčky`;
  - localise forgotten parts of `alban_of_britain_julius_of_caerleon_aaron_of_caerleon_martyrs`;
  - the following keys changed their value in `sk.ts`:
    - `paschal_triduum.season` → `Veľkonočné trojdnie`;
    - `periods.holy_week` → `Svätý týždeň`;
    - `lent.holy_week_day` → `$t(weekdays:{{dow}}, capitalize) Svätého týždňa`;
    - `all_souls` → `Spomienka na všetkých zosnulých veriacich`;
    - `alphonsus_liguori_bishop` → `Svätého Alfonza Máriu de Liguori, biskupa a učiteľa Cirkvi`;
    - `andrew_dung_lac_priest_and_companions_martyrs` → `Svätého Andreja Dung-Laka, kňaza, a spoločníkov, mučeníkov`;
    - `andrew_kim_tae_gon_priest_paul_chong_ha_sang_and_companions_martyrs` → `Svätých Andreja Kima Taegona, kňaza, Pavla Chonga Hasanga a spoločníkov, mučeníkov`;
    - `andrew_zorard_of_nitra_and_benedict_of_skalka_hermits` → `Svätých Andreja Svorada a Beňadika, pustovníkov`;
    - `ansgar_of_hamburg_bishop` → `Svätého Oskara, biskupa`;
    - `assumption` → `Nanebovzatie preblahoslavenej Panny Márie`;
    - `augustine_zhao_rong_priest_and_companions_martyrs` → `Svätých Augustína Zhao Ronga, kňaza, a spoločníkov, mučeníkov`;
    - `baptism_of_the_lord` → `Krst Pána`;
    - `basil_the_great_and_gregory_nazianzen_bishops` → `Svätých Bazila Veľkého a Gregora Naziánzskeho, biskupov a učiteľov Cirkvi`;
    - `benedict_of_nursia_abbot_patron_of_europe` → `Svätého Benedikta, opáta, patróna Európy`;
    - `bridget_of_sweden_religious` → `Svätej Brigity, rehoľníčky`;
    - `bridget_of_sweden_religious_copatroness_of_europe` → `Svätej Brigity, rehoľníčky, patrónky Európy`;
    - `camillus_de_lellis_priest` → `Svätého Kamila z Lellisu, kňaza`;
    - `catherine_of_siena_virgin_copatroness_of_europe` → `Svätej Kataríny Sienskej, panny a učiteľky Cirkvi, patrónky Európy`;
    - `catherine_of_siena_virgin_copatroness_of_italy_and_europe` → `Svätej Kataríny Sienskej, panny a učiteľky Cirkvi, patrónky Talianska a Európy`;
    - `chair_of_saint_peter_the_apostle` → `Katedry svätého Petra, apoštola`;
    - `christ_the_king_sunday` → `Nášho Pána Ježiša Krista, Kráľa neba i zeme`;
    - `clement_i_pope` → `Svätého Klimenta I., pápeža a mučeníka`;
    - `cornelius_i_pope_and_cyprian_of_carthage_bishop_martyrs` → `Svätých Kornela, pápeža, a Cypriána, biskupa, mučeníkov`;
    - `cyril_constantine_the_philosopher_monk_and_methodius_michael_of_thessaloniki_bishop` → `Svätých Cyrila, mnícha, a Metoda, biskupa`;
    - `cyril_constantine_the_philosopher_monk_and_methodius_michael_of_thessaloniki_bishop_copatrons_of_europe` → `Svätých Cyrila, mnícha, a Metoda, biskupa, patrónov Európy`;
    - `cyril_constantine_the_philosopher_monk_and_methodius_michael_of_thessaloniki_bishop_slavic_missionaries_copatrons_of_europe` → `Svätých Cyrila, mnícha, a Metoda, biskupa, slovanských vierozvestov, patrónov Európy`;
    - `dedication_of_consecrated_churches` → `Výročie posviacky chrámov, ktorých deň posviacky nie je známy`;
    - `dedication_of_the_basilica_of_saint_mary_major` → `Výročie posviacky hlavnej mariánskej baziliky v Ríme`;
    - `dedication_of_the_basilicas_of_saints_peter_and_paul_apostles` → `Výročie posviacky bazilík sv. Petra a Pavla, apoštolov`;
    - `denis_of_paris_bishop_and_companions_martyrs` → `Svätého Dionýza, biskupa, a spoločníkov, mučeníkov`;
    - `elizabeth_of_hungary_religious` → `Svätej Alžbety Uhorskej, rehoľníčky`;
    - `fabian_i_pope` → `Svätého Fabiána, pápeža a mučeníka`;
    - `frances_of_rome_religious` → `Svätej Františky Rímskej, rehoľníčky`;
    - `gertrude_the_great_virgin` → `Svätej Gertrúdy, panny`;
    - `hedwig_of_silesia_religious` → `Svätej Hedvigy, rehoľníčky`;
    - `hilary_of_poitiers_bishop` → `Svätého Hilára, biskupa a učiteľa Cirkvi`;
    - `hildegard_of_bingen_abbess` → `Svätej Hildegardy z Bingenu, panny a učiteľky Cirkvi`;
    - `holy_innocents_martyrs` → `Svätých neviniatok, mučeníkov`;
    - `immaculate_conception_of_mary` → `Nepoškvrnené počatie preblahoslavenej Panny Márie`;
    - `immaculate_conception_of_mary_patroness_of_the_philippines` → `Nepoškvrneného počatia preblahoslavenej Panny Márie, patrónky Filipín`;
    - `immaculate_conception_of_mary_patroness_of_the_usa` → `Nepoškvrnené počatie preblahoslavenej Panny Márie, patrónky USA`;
    - `immaculate_heart_of_mary` → `Nepoškvrneného Srdca preblahoslavenej Panny Márie`;
    - `jane_frances_de_chantal_religious` → `Svätej Jany Františky de Chantal, rehoľníčky`;
    - `joachim_and_anne_parents_of_mary` → `Svätých Joachima a Anny, rodičov preblahoslavenej Panny Márie`;
    - `joachim_and_anne_patroness_of_the_province_of_quebec_parents_of_mary` → `Svätých Anny, patrónky Quebecu, a Joachima, rodičov preblahoslavenej Panny Márie`;
    - `john_bosco_priest` → `Svätého Jána Bosca, kňaza`;
    - `john_de_brebeuf_isaac_jogues_priests_and_companions_martyrs` → `Svätých Jána de Brébeuf a Izáka Jogues, kňazov, a ich spoločníkov, mučeníkov`;
    - `john_de_brebeuf_isaac_jogues_priests_and_companions_martyrs_copatrons_of_canada` → `Svätých Jána de Brébeuf a Izáka Joguesa, kňazov, a ich spoločníkov, mučeníkov, patrónov Kanady`;
    - `john_eudes_priest` → `Svätého Jána Eudesa, kňaza`;
    - `john_fisher_bishop_and_thomas_more_martyrs` → `Svätých Jána Fišera, biskupa, a Tomáša Morusa, mučeníkov`;
    - `john_of_avila_priest` → `Svätého Jána z Avily, kňaza a učiteľa Cirkvi`;
    - `john_of_god_duarte_cidade_religious` → `Svätého Jána od Boha, rehoľníka`;
    - `john_of_the_cross_priest` → `Svätého Jána od Kríža, kňaza a učiteľa Cirkvi`;
    - `joseph_of_calasanz_priest` → `Svätého Jozefa Kalazanského`;
    - `joseph_spouse_of_mary` → `Svätého Jozefa, ženícha preblahoslavenej Panny Márie`;
    - `joseph_spouse_of_mary_patron_of_canada` → `Svätého Jozefa, ženícha preblahoslavenej Panny Márie a patróna Kanady`;
    - `juan_diego_cuauhtlatoatzin` → `Svätého Jána Diega Cuauhtlatoatzina`;
    - `laurence_otoole_bishop` → `Svätého Vavrinca O’Toole, biskupa`;
    - `marko_krizin_melchior_grodziecki_and_stephen_pongracz_priests` → `Svätých Marka Križina, Melichara Grodzieckeho a Štefana Pongrácza, kňazov a mučeníkov`;
    - `mary_magdalene_de_pazzi_virgin` → `Svätej Márie Magdalény de Pazzi, panny`;
    - `mary_mother_of_god` → `Oktáva Narodenia Pána. Slávnosť Panny Márie Bohorodičky`;
    - `most_holy_name_of_mary` → `Najsvätejšieho mena Mária`;
    - `nativity_of_mary` → `Narodenie preblahoslavenej Panny Márie`;
    - `our_lady_of_fatima` → `Preblahoslavenej Panny Márie Fatimskej`;
    - `paul_of_the_cross_priest` → `Svätého Pavla od Kríža, kňaza`;
    - `pius_francesco_forgione_priest` → `Svätého Pia z Pietrelciny, kňaza`;
    - `presentation_of_mary` → `Obetovanie preblahoslavenej Panny Márie`;
    - `queenship_of_mary` → `Preblahoslavenej Panny Márie Kráľovnej`;
    - `rita_of_cascia_religious` → `Svätej Rity z Cascie, rehoľníčky`;
    - `seven_holy_founders_of_the_servite_order` → `Siedmich svätých zakladateľov rehole Služobníkov preblahoslavenej Panny Márie`;
    - `sharbel_makhluf_priest` → `Svätého Šarbela Machlúfa, kňaza`;
    - `sixtus_ii_pope_and_companions_martyrs` → `Svätých Sixta II., pápeža, a jeho spoločníkov, mučeníkov`;
    - `teresa_benedicta_of_the_cross_stein_virgin` → `Svätej Terézie Benedikty od Kríža, panny a mučenice`;
    - `teresa_benedicta_of_the_cross_stein_virgin_copatroness_of_europe` → `Svätej Terézie Benedikty od Kríža, panny a mučenice, patrónky Európy`;
    - `teresa_of_jesus_of_avila_virgin` → `Svätej Terézie od Ježiša (z Avily), panny a učiteľky Cirkvi`;
    - `therese_of_the_child_jesus_and_the_holy_face_of_lisieux_virgin` → `Svätej Terézie od Dieťaťa Ježiša (z Lisieux), panny a učiteľky Cirkvi`;
    - `therese_of_the_child_jesus_and_the_holy_face_of_lisieux_virgin_copatroness_of_france` → `Svätej Terézie od Dieťaťa Ježiša (z Lisieux), panny a učiteľky Cirkvi, patrónky Francúzska`;
    - `visitation_of_mary` → `Návšteva preblahoslavenej Panny Márie`;
    - `palm_sunday` → `Palmová (kvetná) nedeľa`;
    - `holy_thursday` → `Štvrtok Svätého týždňa (Zelený štvrtok)`;
    - `thursday_of_the_lords_supper` → `Štvrtok Pánovej večere`;
    - `good_friday` → `Piatok utrpenia Pána (Veľký piatok)`;
    - `holy_saturday` → `Svätá sobota (Biela sobota)`.

</details>

I had to fix the tests too by using [this workaround](https://github.com/jest-community/jest-extended/issues/367#issuecomment-1127269184) (otherwise `jest-extended` would fail to load in tests). Also, I needed to update `jest` (`^28.1.2`) and `jest-extended` (`^2.0.0`). No other change was required to make the tests pass.

### CODE REVIEW

**Comment by tukusejssirs** [comment]
@emagnier, sorry this PR is quite a big one, but I don’t see any valid reason to split it into a few commits nor PRs (I hope agree).

@emagnier, @gtortone, @CodingAleCR, @jarosz, I’d be grateful if you review the changes (esp additions) in your locales (it might be a good idea to do that after the PR was out of the WIP status) and to answer the questions below.

#### l10n reviewers

- `es`: @CodingAleCR:
   - [x] what is the correct Spanish for for English `patron`: `patron` `patróno` or `patrono`?
   - [ ] `dedication_of_the_notre_dame_de_paris_cathedral_paris_france`: is `catedral` written with lowercase `c` when we talk about a specific cathedral in Spanish?
   - [ ] is plural of `Abad` (Abbot) `Abades`?
   - [ ] `marcellus_of_paris_bishop`: `Marcelo` or `Marcello`?
   - [ ] I have found [this Spanish Ordo 2020 _(Calendario Litúrgico Pastoral)_](https://www.conferenciaepiscopal.com.es/wp-content/uploads/2019/11/CLP-2019-2020.pdf) and I am inclined to fix the Spanish locale based on it:
      - in this PR, I’ll most probably only change `Sacerdote` to `Presbítero` and other changes (like using lowercase initial letter of titles and other potential issues) could be fixed in a separate PR;
      - any objection?
   - [ ] `translation_of_the_relics_of_odile_of_alsace_abbess`: `Odilia` or `Otilia`?
   - [ ] `holy_child_of_cebu`: `Divino Niño` or `Santo Niño de Cebú`?
   - [ ] does Spanish Roman Missal use `º` in ordinal numbers and thus celebration names?
   - [ ] below is a list of 68 changes in `es.ts`; proof them all please:
  
      <details>
         <summary><code>es.ts</code> changes</summary>
       
      ```ts
      adelaide_of_burgundy_empress: 'Santa Adelaida de Borgoña, Emperatriz',
      adelphus_of_metz_bishop: 'San Adelfus de Métis, Obispo',
      all_saints_of_the_archdiocese_of_paris: 'Todos los Santos de la Arquidiócesis de París',
      all_saints_of_the_diocese_of_saint_denis: 'Todos los Santos de la Diócesis de Saint-Denis',
      alphonsus_mary_liguori_bishop: 'San Alfonso María de Ligorio, Obispo y Doctor de la Iglesia',
      amandus_of_strasbourg_bishop: 'San Amand de Estrasburgo, Obispo',
      amarin_of_alsace_abbot: 'San Amarino, Abad y Mártir',
      arbogast_of_strasbourg_bishop_patron_of_the_archdiocese_of_strasbourg: 'San Arbogast, Obispo y Patrono de la Arquidiócesis de Estrasburgo',
      arbogast_of_strasbourg_bishop: 'San Arbogast, Obispo',
      audoen_of_rouen_bishop: 'San Audoeno, Obispo',
      aurelia_of_strasbourg_virgin: 'Santa Aurelia de Estrasburgo, Vírgen',
      benedict_of_aniane_abbot: 'San Benito de Aniano, Abad',
      blessed_martyrs_of_paris: 'Beatos Mártires de París en la Revolución Francesa',
      brigid_of_kildare_virgin: 'Santa Brígida de Kildare, Abadesa',
      carmelites_of_compiegne_virgins_and_martyrs: 'Beatas Carmelitas de Compiègne, Vírgenes y Mártires',
      catherine_of_siena_virgin_copatroness_of_europe: 'Santa Catalina de Siena, Vírgen, Doctora de la Iglesia y Patrona Secundaria de Europa',
      catherine_of_siena_virgin_copatroness_of_italy_and_europe: 'Santa Catalina de Siena, Vírgen, Doctora de la Iglesia y Patrona Secundaria de Italia y Europa',
      catherine_of_siena_virgin: 'Santa Catalina de Siena, Vírgen y Doctora de la Iglesia',
      catherine_zoe_laboure_virgin: 'Santa Catalina Labouré, Vírgen',
      ceraunus_of_paris_bishop: 'San Cerauno de París, Obispo',
      charles_of_jesus_de_foucauld: 'Santos Carlos de Foucauld, Sacerdote',
      daniel_brottier_priest: 'Beato Daniel Brottier, Sacerdote',
      dedication_of_the_cathedral_basilica_of_saint_denis_france: 'Dedicación de la Catedral Basílica de Saint-Denis, Francia',
      dedication_of_the_cathedral_of_notre_dame_de_strasbourg_france: 'Dedicación de la Catedral de Notre-Dame de Strasbourg, Francia',
      dedication_of_the_notre_dame_de_paris_cathedral_paris_france: 'Dedicación de la catedral de Notre-Dame de París, Francia',
      denis_of_paris_bishop_patron_of_the_archdiocese_of_paris: 'San Dionisio, Obispo y Mártir, Patrono de la Arquidiócesis de París',
      denis_of_paris_bishop_patron_of_the_city_and_of_the_diocese_of_saint_denis: 'San Dionisio, Obispo y Mártir, Patrono de la ciudad y de la Diócesis de Saint-Denis',
      divine_mercy_sunday: '{{week}}º domingo de Pascua o Domingo de la Divina Misericordia',
      eligius_of_noyon_bishop: 'San Eligio, Obispo',
      eucharius_of_trier_bishop: 'San Euchario, Obispo',
      eugenia_of_alsace_and_attala_of_alsace_virgins: 'Santas Eugènia y Attala, Vírgenes',
      florentius_of_strasbourg_bishop: 'San Florencio, Obispo',
      frederic_ozanam_founder: 'Beato Federico Ozanam, Fundador',
      germain_of_paris_bishop: 'San Germán, Obispo',
      immaculate_conception_of_the_blessed_virgin_mary: 'Inmaculada Concepción de María',
      innocent_v_pope: 'Beato Inocencio V, Papa',
      isabelle_of_france_virgin: 'Beata Isabel de Francia, Vírgen',
      landry_of_paris_bishop: 'San Landerico de París, Obispo',
      leodegar_of_autun_bishop: 'San Leodegario de Autun, Obispo y Mártir',
      louise_de_marillac_religious: 'Santa Luisa de Marillac, Religiosa',
      ludan_of_scotland_pilgrim: 'San Ludano, peregrino',
      madeleine_sophie_barat_virgin: 'Santa Magdalena Sofía Barat, Vírgen',
      marcellus_of_paris_bishop: 'San Marcelo de París, Obispo',
      marie_eugenie_of_jesus_milleret_de_brou_virgin: 'Santa María Eugenia de Jesús Milleret de Brou, Vírgen y Fundatrice',
      mary_of_the_incarnation_barbara_acarie_religious: 'Beata María de la Encarnación Bárbara Acarie, Religiosa',
      mary_of_the_incarnation_marie_guyart_religious: 'Santa María de la Encarnación María Guyart, Religiosa',
      mary_of_the_providence_eugenie_smet_virgin: 'Beata María de la Providencia Eugenia Smet, Vírgen',
      mary_of_the_sacred_heart_sophie_therese_de_soubiran_la_louviere_virgin: 'Beata María Teresa de Soubiran La Louvière, Vírgen',
      maternus_of_cologne_bishop: 'San Materno, Obispo',
      maternus_of_cologne_valerius_of_trier_and_eucharius_of_trier_bishops: 'Santos Materno, Valerio y Eucario, Obispos',
      mederic_of_autun_and_droctoveus_of_autun_abbots: 'Santos Mederico y Droctoveo, Abades',
      modestus_andlauer_and_andrew_bauer_martyrs: 'San Modesto Andlauer y Andrés Bauer, Mártires',
      modestus_andlauer_martyr: 'San Modesto Andlauer, Mártir',
      morand_of_cluny_monk: 'San Morando, Monje',
      nicholas_barre_priest: 'Beato Nicolás Barré, Sacerdote',
      our_lady_of_the_miraculous_medal: 'Nuestra Señora de la Medalla Milagrosa',
      our_lady_refuge_of_sinners: 'Nuestra Señora, refugio de los pecadores',
      richardis_of_swabia_empress: 'Santa Ricarda, Emperatriz',
      rosalie_jeanne_marie_rendu_virgin: 'Beata Rosalía Rendu, Vírgen',
      sunday_of_the_word_of_god: '{{week}}º domingo del Tiempo Ordinario, o domingo de la Palabra de Dios',
      teresa_of_jesus_of_avila_virgin: 'Santa Teresa de Jesús, Vírgen y Doctora',
      therese_of_the_child_jesus_and_the_holy_face_of_lisieux_virgin_copatroness_of_france: 'Santa Teresita del Niño Jesús, Vírgen y Doctora, Patrona Secundaria de Francia',
      therese_of_the_child_jesus_and_the_holy_face_of_lisieux_virgin: 'Santa Teresita del Niño Jesús, Vírgen y Doctora',
      thomas_jean_georges_rehm_priest: 'Beato Tomás Juan Jorge Rehm, Sacerdote y Mártir',
      translation_of_the_relics_of_odile_of_alsace_abbess: 'Traslado de los restos de santa Odilia',
      urban_i_pope: 'San Urbano I, Papa',
      valerius_of_trier_bishop: 'San Valerio, Obispo',
      wendelin_of_trier_hermit: 'San Vendelino, Ermitaño',
      ```
   
      </details>

- `fr`: @emagnier:
   - [x] `blessed_martyrs_of_paris`: are Blessed Martyrs of Paris and Blessed Martyrs of French Revolution two different groups of blesseds or not? What is the best way to translate this string?
      - `Blessed Martyrs of Paris`;
      - `Blessed [Parisian] Martyrs of French Revolution`;
   - [x] I suggest to replace `✝` (U+271D) with `†` (U+2020) in `fr.ts.` (currently, we use both glyphs);
   - [x] use either `siècle` or `s.` in `fr.ts` (currently, we use both of them);
   - [x] some death dates in `fr.ts` are in brackets, other not; can we put them _always_ in brackets?
   - [x] `brigid_of_kildare_virgin`: I have no idea how to _really_ solve the issue that some particular calendars use different titles for the same person (in this case, in `ireland.ts`, they use `Virgin`, but in `france.strasbourg.ts`, they use `Abbess`). I understand that it is not a big deal in this particular case, because these two calendars use different keys, but in other cases it is a bit bigger deal. I see only one way to solve this truly is to fix #201 and #232;
   - [x] `dedication_of_the_notre_dame_de_paris_cathedral_paris_france` and `dedication_of_the_cathedral_of_notre_dame_de_strasbourg_france`: should we localise `Notre-Dame de {Paris,Strasbourg}` to `Our Lady of {Paris,Strasbourg}`?
   - [x] `denis_of_paris_bishop_patron_of_the_diocese_of_saint_denis`: consider creating two keys for each patronages (one for the city, the other for the diocese; this will be solved in #371);
   - [x] `sunday_of_the_word_of_god`: could we add `dimanche` after `ou` word, i.e. `Troisième dimanche du Temps Ordinaire, ou dimanche de la Parole de Dieu`? Or maybe `Dimanche`, as it is another celebration name and therefore might be considered a proper name (of the celebration) in French;
   - [x] [not a question, just an info] `merry_and_saint_droctovee_abbots`: according to [[Wiki] _Église Saint-Merri_](https://fr.wikipedia.org/wiki/%C3%89glise_Saint-Merri), Merry/Merri is a contracted name from [Saint Mederic](https://en.wikipedia.org/wiki/Mederic_(monk)) ([fr](https://fr.wikipedia.org/wiki/Saint_M%C3%A9d%C3%A9ric)); also, it is quite strange that the celebration name in the French Proper contains the canonisation level twice (once for each saint);

- `it`: @gtortone:
   - [x] `aurelia_of_strasbourg_virgin`: `Aurèlia` or `Aurelia`?
   - [x] `arbogast_of_strassburg_bishop`: do you prefer `Arbogaste` or `Arbogasto`?
   - [x] `eligius_of_noyon_bishop`: `Sant’Eligio` or `sant’Alo` or `sant’Alò` or `san Lo` ([src](https://it.wikipedia.org/wiki/Eligio_di_Noyon))?
   - [x] `mary_of_the_providence_eugenie_smet_virgin`: I used `Eugènia` (for the same reason as `Aurèlia`), however, on [Wiki](https://it.wikipedia.org/wiki/Eug%C3%A9nie_Smet), they write it as `Eugenia`;
   - [x] `rosalie_jeanne_marie_rendu_virgin`: `Rosalia` or `Rosàlia`?
   - [x] `translation_of_the_relics_of_odile_of_alsace_abbess`: `Odilia` or `Odìlia` or `Otilia` or `Otîlia`?
   - [x] is plural of `abate` (Abbot) `abati`?
   - [x] below is a list of 62 changes in `it.ts`; proof them all please:
   
      <details>
         <summary><code>it.ts</code> changes</summary>
   
      ```ts
      adelaide_of_burgundy_empress: 'Santa Adelaide di Borgogna, imperatrice',
      adelphus_of_metz_bishop: 'Sant’Adelfo di Metz, vescovo',
      all_saints_of_the_archdiocese_of_paris: 'Tutti i Santi dell’Arcidiocesi di Parigi',
      all_saints_of_the_diocese_of_saint_denis: 'Tutti i Santi della Diocesi di Saint-Denis',
      amandus_of_strasbourg_bishop: 'Sant’Amando di Strasburgo, vescovo',
      amarin_of_alsace_abbot: 'Sant’Amarino, abate e martire',
      arbogast_of_strasbourg_bishop_patron_of_the_archdiocese_of_strasbourg: 'Sant’Arbogasto, vescovo e patrono dell’Arcidiocesi di Strasburgo',
      arbogast_of_strasbourg_bishop: 'Sant’Arbogasto, vescovo',
      audoen_of_rouen_bishop: 'Sant’Audoeno, vescovo',
      aurelia_of_strasbourg_virgin: 'Sant’Aurèlia di Strasburgo, vergine',
      benedict_of_aniane_abbot: 'San Benedetto d’Aniane, abate',
      blessed_martyrs_of_paris: 'Beati Martiri della Rivoluzione francese',
      brigid_of_kildare_virgin_copatroness_of_ireland: 'Saint Brigida di Kildare, badessa e and patrona secondaria d’Irlanda',
      brigid_of_kildare_virgin: 'Saint Brigida di Kildare, badessa',
      carmelites_of_compiegne_virgins_and_martyrs: 'Beati carmelitani di Compiègne, vergini e martiri',
      catherine_zoe_laboure_virgin: 'Santa Caterina Labourè, vergine',
      ceraunus_of_paris_bishop: 'San Cerauno di Parigi, vescovo',
      charles_of_jesus_de_foucauld: 'San Charles de Foucauld, sacerdote',
      daniel_brottier_priest: 'Beato Daniel Brottier, sacerdote',
      dedication_of_the_cathedral_basilica_of_saint_denis_france: 'Dedicazione della Basilica Cattedrale di Saint-Denis, Francia',
      dedication_of_the_cathedral_of_notre_dame_de_strasbourg_france: 'Dedicazione della Cattedrale di Notre-Dame de Strasbourg, Francia',
      dedication_of_the_notre_dame_de_paris_cathedral_paris_france: 'Dedicazione della Cattedrale di Notre-Dame de Paris, Francia',
      denis_of_paris_bishop_patron_of_the_archdiocese_of_paris: 'San Dionigi, vescovo e martire, patrono dell’Arcidiocesi di Parigi',
      denis_of_paris_bishop_patron_of_the_city_and_of_the_diocese_of_saint_denis: 'San Dionigi, vescovo e martire, patrono della città e della Diocesi di Saint-Denis',
      divine_mercy_sunday: 'II domenica di Pasqua o Domenica della Divina Misericordia',
      eligius_of_noyon_bishop: 'Sant’Eligio, vescovo',
      eucharius_of_trier_bishop: 'Sant’Eucario, vescovo',
      eugenia_of_alsace_and_attala_of_alsace_virgins: 'Santas Eugenia e Attala, vergini',
      fidelis_of_sigmaringen_priest: 'San Fedele da Sigmaringen, sacerdote e martire',
      florentius_of_strasbourg_bishop: 'San Fiorenzo, vescovo',
      frederic_ozanam_founder: 'Beato Federico Ozanam, fondatore',
      germain_of_paris_bishop: 'San Germano di Parigi, vescovo',
      innocent_v_pope: 'Beato Innocenzo V, Papa',
      isabelle_of_france_virgin: 'Beata Isabella di Francia, vergine',
      landry_of_paris_bishop: 'San Landerico di Parigi, vescovo',
      leodegar_of_autun_bishop: 'San Leodegario di Autun, vescovo e martire',
      louise_de_marillac_religious: 'Santa Luisa di Marillac, religiosa',
      ludan_of_scotland_pilgrim: 'San Ludano, pellegrino',
      madeleine_sophie_barat_virgin: 'Santa Maddalena Sofia Barat, vergine',
      marcellus_of_paris_bishop: 'San Marcello di Parigi, vescovo',
      marie_eugenie_of_jesus_milleret_de_brou_virgin: 'Santa Maria Eugenia di Gesù Milleret de Brou, vergine e fondatrice',
      mary_of_the_incarnation_barbara_acarie_religious: 'Beata Maria dell’Incarnazione Barbara Acarie, religiosa',
      mary_of_the_incarnation_marie_guyart_religious: 'Santa Maria dell’Incarnazione Maria Guyart, religiosa',
      mary_of_the_providence_eugenie_smet_virgin: 'Beata Maria della Provvidenza Eugènia Smet, vergine',
      mary_of_the_sacred_heart_sophie_therese_de_soubiran_la_louviere_virgin: 'Beata Maria Teresa de Soubiran La Louvière, vergine',
      maternus_of_cologne_bishop: 'San Materno, vescovo',
      maternus_of_cologne_valerius_of_trier_and_eucharius_of_trier_bishops: 'Santi Materno, Valerio e Eucario, vescovi',
      mederic_of_autun_and_droctoveus_of_autun_abbots: 'Santi Mederico e Drottoveo, abati',
      modestus_andlauer_and_andrew_bauer_martyrs: 'San Modesto Andlauer e Andrea Bauer, martiri',
      modestus_andlauer_martyr: 'San Modesto Andlauer, martire',
      morand_of_cluny_monk: 'San Morando, monaco',
      nicholas_barre_priest: 'Beato Nicola Barré, sacerdote',
      our_lady_of_the_miraculous_medal: 'Beata Vergine Maria della Medaglia Miracolosa',
      our_lady_refuge_of_sinners: 'Beata Vergine Maria, rifugio dei peccatori',
      richardis_of_swabia_empress: 'Santa Riccarda, imperatrice',
      rosalie_jeanne_marie_rendu_virgin: 'Beata Rosalia Rendu, vergine',
      sunday_of_the_word_of_god: '{{week, romanize}} domenica del Tempo Ordinario, o Domenica della Parola di Dio',
      thomas_jean_georges_rehm_priest: 'Beato Tommaso Jean-Georges Rehm, sacerdote e martire',
      translation_of_the_relics_of_odile_of_alsace_abbess: 'Traslazione delle reliquie di santa Odilia',
      urban_i_pope: 'Sant’Urbano I, papa',
      valerius_of_trier_bishop: 'San Valerio, vescovo',
      wendelin_of_trier_hermit: 'San Vendelino, eremita',
      ```
   
      </details>

- `pl`: @jarosz:
   - [ ] `brigid_of_kildare_virgin`: what word do you use for `abbess`? `opatka`, `ksieni` or `przeorysza`?
   - [ ] `dedication_of_the_notre_dame_de_paris_cathedral_paris_france` and `dedication_of_the_cathedral_basilica_of_saint_denis_france`: is `Katedry` and `Bazyliky Katedralnej` written with uppercase initial letters or not?
   - [ ] `Marii` or `Maryi`? Should the latter be used only for Our Lady, while `Marii` should be used for other Marys?
   - [ ] `sunday_of_the_word_of_god`: is `lub` the correct word to use for `or`?
   - [ ] below is a list of 63 changes in `pl.ts`; proof them all please:
   
      <details>
         <summary><code>pl.ts</code> changes</summary>
   
      ```ts
      adelaide_of_burgundy_empress: 'Św. Adelajdy Burgundzkiej, cesarzowy',
      adelphus_of_metz_bishop: 'Św. Adelfa z Metz, biskupa',
      all_saints_of_the_archdiocese_of_paris: 'Wszystkich Świętych archidiecezji paryskiej',
      all_saints_of_the_diocese_of_saint_denis: 'Wszystkich Świętych diecezji Saint-Denis',
      amandus_of_strasbourg_bishop: 'Św. Amanda ze Strasburga, biskupa',
      amarin_of_alsace_abbot: 'Św. Amarina, opata i męczennika',
      arbogast_of_strasbourg_bishop_patron_of_the_archdiocese_of_strasbourg: 'Św. Arbogasta, biskupa i patrona archidiecezji Strasburga',
      arbogast_of_strasbourg_bishop: 'Św. Arbogasta, biskupa',
      audoen_of_rouen_bishop: 'Św. Audoena, biskupa',
      aurelia_of_strasbourg_virgin: 'Św. Aurelie ze Strasburga, dziewicy',
      benedict_of_aniane_abbot: 'Św. Benedykt z Anianu, opata',
      blessed_martyrs_of_paris: 'Bł. Męczennicy z Paryża',
      brigid_of_kildare_virgin_copatroness_of_ireland: 'Św. Brygidy z Kildare, dziewicy i patronki Irlandii',
      brigid_of_kildare_virgin: 'Św. Brygidy z Kildare, opatky',
      carmelites_of_compiegne_virgins_and_martyrs: 'Bł. karmelitanek z Compiègne, dziewic i męczennic',
      catherine_zoe_laboure_virgin: 'Św. Katarzyny Labouré, dziewicy',
      ceraunus_of_paris_bishop: 'Św. Cerana z Paryża, biskupa',
      charles_of_jesus_de_foucauld: 'Św. Karola de Foucauld, prezbitera',
      daniel_brottier_priest: 'Bł. Daniela Brottier, prezbitera',
      dedication_of_the_cathedral_basilica_of_saint_denis_france: 'Rocznica poświęcenia Bazyliky Katedralnej Saint-Denis, Francja',
      dedication_of_the_cathedral_of_notre_dame_de_strasbourg_france: 'Rocznica poświęcenia Katedry Notre-Dame de Strasbourg, Francja',
      dedication_of_the_notre_dame_de_paris_cathedral_paris_france: 'Rocznica poświęcenia Katedry Notre-Dame de Paris, Francja',
      denis_of_paris_bishop_patron_of_the_archdiocese_of_paris: 'Św. Dionizego, biskupa i męczennika, patrona archidiecezji paryskiej',
      denis_of_paris_bishop_patron_of_the_city_and_of_the_diocese_of_saint_denis: 'Św. Dionizego, biskupa i męczennika, patrona miasta i diecezji Saint-Denis',
      divine_mercy_sunday: '2 Niedziela Wielkanocna czyli Niedziela Miłosierdzia Bożego',
      eligius_of_noyon_bishop: 'Św. Eligiusza, biskupa',
      eucharius_of_trier_bishop: 'Św. Euchariusza, biskupa',
      eugenia_of_alsace_and_attala_of_alsace_virgins: 'Św. Eugenii i Attali, dziewic',
      florentius_of_strasbourg_bishop: 'Św. Florencjusza, biskupa',
      frederic_ozanam_founder: 'Bł. Fryderyka Ozanama, założyciela',
      germain_of_paris_bishop: 'Św. Germana, biskupa',
      innocent_v_pope: 'Bł. Innocentego V, papieża',
      isabelle_of_france_virgin: 'Bł. Izabeli Francuskiej, dziewicy',
      landry_of_paris_bishop: 'Św. Landeryka z Paryża, biskupa',
      leodegar_of_autun_bishop: 'Św. Leodegara z Autun, biskupa i męczennika',
      louise_de_marillac_religious: 'Św. Ludwiky de Marillac, religiosæ',
      ludan_of_scotland_pilgrim: 'Św. Ludana, pielgrzyma',
      madeleine_sophie_barat_virgin: 'Św. Magdaleny Zofii Barat, dziewicy',
      marcellus_of_paris_bishop: 'Św. Marcelego z Paryża, biskupa',
      marie_eugenie_of_jesus_milleret_de_brou_virgin: 'Św. Marii Eugenii od Jezusa Milleret de Brou, dziewicy i założycielky',
      mary_of_the_incarnation_barbara_acarie_religious: 'Bł. Marii od Wcielenia Barbary Acarie, zakonnicy',
      mary_of_the_incarnation_marie_guyart_religious: 'Św. Marii od Wcielenia Marii Guyart, zakonnicy',
      mary_of_the_providence_eugenie_smet_virgin: 'Bł. Marii od Opatrzności Eugenii Smet, dziewicy',
      mary_of_the_sacred_heart_sophie_therese_de_soubiran_la_louviere_virgin: 'Bł. Marii Teresy de Soubiran La Louvière, dziewicy',
      maternus_of_cologne_bishop: 'Św. Maternusa, biskupa',
      maternus_of_cologne_valerius_of_trier_and_eucharius_of_trier_bishops: 'Św. Maternusa, Waleriusza i Euchariusza, biskupów',
      mederic_of_autun_and_droctoveus_of_autun_abbots: 'Św. Mederyka i Droctovæi, opatów',
      modestus_andlauer_and_andrew_bauer_martyrs: 'Św. Modesta Andlauera i Andrzeja Bauera, męczenników',
      modestus_andlauer_martyr: 'Św. Modesta Andlauera, męczennika',
      morand_of_cluny_monk: 'Św. Moranda, mnicha',
      nicholas_barre_priest: 'Bł. Mikołaja Barré, prezbitera',
      our_lady_of_the_miraculous_medal: 'Najświętszej Maryi Panny od Cudownego Medalika',
      our_lady_refuge_of_sinners: 'Najświętszej Maryi Panny, Ucieczki Grzeszników',
      peter_sanz_bishop: 'Św. Piotra Sanza, biskupa i męczennika',
      pontian_i_pope_and_hippolytus_of_rome_priest: 'Świętych męczenników Poncjana, papieża i Hipolita, prezbitera',
      richardis_of_swabia_empress: 'Św. Ryszardy, cesarzowy',
      rosalie_jeanne_marie_rendu_virgin: 'Bł. Rozalii Rendu, panny',
      sunday_of_the_word_of_god: '{{week}}. Niedziela zwykła, lub Niedziela Słowa Bożego',
      thomas_jean_georges_rehm_priest: 'Bł. Tomasza Jana Jerzego Rehma, prezbitera i męczennika',
      translation_of_the_relics_of_odile_of_alsace_abbess: 'Przeniesienie relikwii św. Otylii',
      urban_i_pope: 'Św. Urbana I, papieża',
      valerius_of_trier_bishop: 'Św. Waleriusza, biskupa',
      wendelin_of_trier_hermit: 'Św. Wendelina, pustelnika',
      ```
   
      </details>

- `pt-br`: @HenriqueDerosa:
   - [ ] `denis_of_paris_bishop_and_companions_martyrs`, `denis_of_paris_bishop_patron_of_the_archdiocese_of_paris`, and `denis_of_paris_bishop_patron_of_the_diocese_of_saint_denis`: should his name be `Dinis` or `Dionísio`?
   - [ ] `eligius_of_noyon_bishop`: `Santo Elígio` or `Santo Elói`?
   - [ ] `eugenia_of_alsace_and_attala_of_alsace_virgins`: are `Eugenia` and `Attala` names correct? Are those names spelled that way in Portuguese?
   - [ ] `ludan_of_scotland_pilgrim`: I could not find any mention of St Ludan in Portuguese, therefore I could not verify the translation of the key;
   - [ ] `our_lady_mother_of_divine_providence_patroness_of_puerto_rico`: add translation of `Patronness of Porto Rico`;
   - [ ] `our_lady_of_aparecida_patroness_of_brazil`: add translation of `Patronness of Brazil`;
   - [ ] `our_lady_of_hungary_patroness_of_hungary`: add translation of `Patroness of Hungary`;
   - [ ] below is a list of 65 changes in `pt-br.ts`; proof them all please:
   
      <details>
         <summary><code>pt-br.ts</code> changes</summary>
   
      ```ts
      adelaide_of_burgundy_empress: 'Santa Adelaide de Borgonha, imperatriz',
      adelphus_of_metz_bishop: 'São Adelfus de Métis, bispo',
      all_saints_of_the_archdiocese_of_paris: 'Todos os Santos da Arquidiocese de Paris',
      alphonsus_mary_liguori_bishop: 'Santo Afonso Maria Liguori, bispo e doutor da Igreja',
      amandus_of_strasbourg_bishop: 'São Amand de Estrasburgo, bispo',
      amarin_of_alsace_abbot: 'São Amarino, abade e mártir',
      arbogast_of_strasbourg_bishop_patron_of_the_archdiocese_of_strasbourg: 'São Arbogasto, bispo e patrono da Arquidiocese de Estrasburgo',
      arbogast_of_strasbourg_bishop: 'São Arbogasto, bispo',
      audoen_of_rouen_bishop: 'São Audoeno, bispo',
      aurelia_of_strasbourg_virgin: 'Santa Aurélia de Estrasburgo, virgem',
      benedict_of_aniane_abbot: 'São Bento de Aniane, abade',
      blessed_martyrs_of_paris: 'Beatos mártires da Revolução Francesa',
      brigid_of_kildare_virgin_copatroness_of_ireland: 'Santa Brígida de Kildare, virgem e copatrona da Irlanda',
      brigid_of_kildare_virgin: 'Santa Brígida de Kildare, abadessa',
      carmelites_of_compiegne_virgins_and_martyrs: 'Beatas Carmelitas de Compiègne, virgens e mártires',
      catherine_zoe_laboure_virgin: 'Santa Catarina Labouré, virgem',
      ceraunus_of_paris_bishop: 'São Cerauno de Paris, bispo',
      charles_of_jesus_de_foucauld: 'São Carlos de Foucauld, presbítero',
      commemoration_of_all_the_faithful_departed: 'Comemoração de Todos os Fiéis Defuntos',
      daniel_brottier_priest: 'Beato Daniel Brottier, presbítero',
      dedication_of_the_cathedral_basilica_of_saint_denis_france: 'Dedicação da Catedral Basílica de Saint-Denis, França',
      dedication_of_the_cathedral_of_notre_dame_de_strasbourg_france: 'Dedicação da Catedral de Notre-Dame de Estrasburgo, França',
      dedication_of_the_notre_dame_de_paris_cathedral_paris_france: 'Dedicação da Catedral de Notre-Dame de Paris, França',
      denis_of_paris_bishop_and_companions_martyrs: 'São Dionísio, bispo, e companheiros, mártires',
      denis_of_paris_bishop_patron_of_the_archdiocese_of_paris: 'São Dionísio, bispo e mártir, patrono da Arquidiocese de Paris',
      denis_of_paris_bishop_patron_of_the_city_and_of_the_diocese_of_saint_denis: 'São Dionísio, bispo e mártir, patrono da Cidade e da Diocese de Saint-Denis',
      divine_mercy_sunday: '{{week}}º Domingo do Tempo Pascal ou Domingo da Misericórdia',
      eligius_of_noyon_bishop: 'Santo Elígio, bispo',
      eucharius_of_trier_bishop: 'Santo Eucario, bispo',
      eugenia_of_alsace_and_attala_of_alsace_virgins: 'Santas Eugenia e Attala, virgens',
      florentius_of_strasbourg_bishop: 'São Florêncio, bispo',
      frederic_ozanam_founder: 'Beato Frederico Ozanam, fundador',
      germain_of_paris_bishop: 'São Germano, bispo',
      innocent_v_pope: 'Papa Beato Inocêncio V',
      isabelle_of_france_virgin: 'Beata Isabel de França, virgem',
      landry_of_paris_bishop: 'São Landry de Paris, bispo',
      leodegar_of_autun_bishop: 'São Leodegar de Autun, bispo e mártir',
      louise_de_marillac_religious: 'Santa Luísa de Marillac, religiosa',
      ludan_of_scotland_pilgrim: 'São Ludan, peregrino',
      madeleine_sophie_barat_virgin: 'Santa Magdalena Sofia Barat, virgem',
      marcellus_of_paris_bishop: 'São Marcelo de Paris, bispo',
      marie_eugenie_of_jesus_milleret_de_brou_virgin: 'Santa Marie-Eugénie de Jésus Milleret de Brou, virgem e fundadora',
      mary_of_the_incarnation_barbara_acarie_religious: 'Beata Maria da Encarnação Bárbara Acarie, religiosa',
      mary_of_the_incarnation_marie_guyart_religious: 'Santa Maria da Encarnação Maria Guyart, religiosa',
      mary_of_the_providence_eugenie_smet_virgin: 'Beata Maria da Providência Eugênia Smet, virgem',
      mary_of_the_sacred_heart_sophie_therese_de_soubiran_la_louviere_virgin: 'Beata Maria Teresa de Soubiran La Louvière, virgem',
      maternus_of_cologne_bishop: 'São Materno, bispo',
      maternus_of_cologne_valerius_of_trier_and_eucharius_of_trier_bishops: 'Santos Materno, Valério e Eucário, bispos',
      maximilian_mary_raymund_kolbe_priest: 'São Maximiliano Maria Kolbe, presbítero e mártir',
      mederic_of_autun_and_droctoveus_of_autun_abbots: 'Santos Mederico e Droctoveo, abades',
      modestus_andlauer_and_andrew_bauer_martyrs: 'Santos Modesto Andlauer e André Bauer, mártires',
      modestus_andlauer_martyr: 'São Modesto Andlauer, mártir',
      morand_of_cluny_monk: 'São Morando, monge',
      nicholas_barre_priest: 'Beato Nicolau Barré, presbítero',
      our_lady_of_the_miraculous_medal: 'Nossa Senhora da Medalha Milagrosa',
      our_lady_refuge_of_sinners: 'Nossa Senhora, Refúgio dos Pecadores',
      pius_francesco_forgione_priest: 'São Pio de Pietrelcina, presbítero',
      richardis_of_swabia_empress: 'Santa Ricarda, imperatriz',
      rosalie_jeanne_marie_rendu_virgin: 'Beata Rosália Rendu, virgem',
      sunday_of_the_word_of_god: '{{week}}º Domingo do Tempo Comum, ou Domingo da Palavra de Deus',
      thomas_jean_georges_rehm_priest: 'Beato Tomás João Jorge Rehm, presbítero e mártir',
      translation_of_the_relics_of_odile_of_alsace_abbess: 'Trasladação dos restos mortais da Santa Odília',
      urban_i_pope: 'Papa São Urbano I',
      valerius_of_trier_bishop: 'São Valério, bispo',
      wendelin_of_trier_hermit: 'São Vendelino, eremita',
      ```
   
      </details>

---

[fixed] @emagnier, is this needed in `ireland.ts`, when St Pius celebration is already memorial in the GRC? Can we safely delete it?

```ts
// Ireland
pius_francesco_forgione_priest: {
  precedence: Precedences.GeneralMemorial_10,
  dateDef: { month: 9, date: 23 },
},

// GRC
pius_francesco_forgione_priest: {
  precedence: Precedences.GeneralMemorial_10,
  dateDef: { month: 9, date: 23 },
},
```

#### TODO:

- [x] finish the PR (see the PR description);
- [x] finish the list of changed key names;
- [x] sort all the keys in all locales (`name` subobject only);
- [x] sort all definitions in `lib/catalog/martyrology.ts`;
- [x] lint the changed files (`npx prettier -w lib`):
   - @emagnier, the `printWidth` option of `prettier` complicates my life when sorting the keys, therefore prior to any big changes in the l10n files, I always remove the line breaks between the key name and key value;
- [x] rebase the PR on top of `dev`;
- [x] split #295 issue prior to merging this PR:
   - some change require some additional work prior to tending them.

**Comment by CodingAleCR** [comment]
@tukusejssirs the Spanish for the word in English `patron` is `patrón`. Although `patrono` is also accepted as well, and is also used according to the context. In fact, for she/her usage you would use the word `patrona`.

The plural form is `patronos` for he/him and `patronas` for she/her.

The usual usage for a Saint might go something like `patron of lost causes` which would translate to Spanish as `patrono de las causas perdidas`. Hope this clarifies your question. Cheers!

File: lib/locales/es.ts [hunk 1]
```diff
@@ -231,19 +206,20 @@ export const locale: Locale = {
...
     carlos_manuel_rodriguez_santiago: 'Beato Carlos Manuel Rodriguez',
     casimir_of_poland: 'San Casimiro',
     catherine_of_alexandria_virgin: 'Santa Catalina de Alexandria, Vírgen y Mártir',
     catherine_of_saint_augustine_de_simon_de_longpre_virgin: 'Beata María Catalina de San Agustín, Vírgen',
     catherine_of_siena_virgin: 'Santa Catalina de Siena, Vírgen y Doctor de la Iglesia',
-    catherine_of_siena_virgin_copatroness_of_europe:
-      'Santa Catalina de Siena, Vírgen, Doctor de la Iglesia y Patrona Secundaria de Europa',
-    catherine_of_siena_virgin_copatroness_of_italy_and_europe:
-      'Santa Catalina de Siena, Vírgen, Doctor de la Iglesia y Patrona Secundaria de Italia y Europa',
+    catherine_of_siena_virgin_copatroness_of_europe: 'Santa Catalina de Siena, Vírgen, Doctor de la Iglesia y Patrona Secundaria de Europa',
```
Comment (CodingAleCR) [inline lib/locales/es.ts]: Ideally use `Doctora` instead of `Doctor` since it's a woman we are referring to.

File: lib/locales/es.ts [hunk 2]
```diff
@@ -286,18 +267,22 @@ export const locale: Locale = {
     hedwig_of_silesia_religious: 'Santa Eduviges, Religiosa',
     helena_of_constantinople: 'Santa Elena',
     holy_child_of_cebu: 'Divino Niño', // TODO: Should it not be rather `Santo Niño de Cebú`?
+    holy_family: 'Sagrada Familia',
     holy_innocents_martyrs: 'Santos Inocentes, Mártires',
+    holy_saturday: 'Sábado Santo',
+    holy_thursday: 'Jueves Santo',
     ignatius_of_antioch_bishop: 'San Ignacio de Antioquía, Obispo y Mártir',
     ignatius_of_loyola_priest: 'San Ignacio de Loyola, Sacerdote',
+    immaculate_conception_of_mary: 'Inmaculada Concepción',
```
Comment (CodingAleCR) [inline lib/locales/es.ts]: This should still refer to Mary as `Inmaculada Concepción de María`

**Review by CodingAleCR — COMMENTED** [review]
A couple of minor issues with some of them, the new additions seem fine though

File: lib/locales/es.ts (hunk 1 above)
Comment (tukusejssirs) [reply lib/locales/es.ts]: Thanks! I also fixed this in the following keys:
- `catherine_of_siena_virgin`;
- `catherine_of_siena_virgin_copatroness_of_europe`;
- `catherine_of_siena_virgin_copatroness_of_italy_and_europe`;
- `teresa_of_jesus_of_avila_virgin`;
- `therese_of_the_child_jesus_and_the_holy_face_of_lisieux_virgin`;
- `therese_of_the_child_jesus_and_the_holy_face_of_lisieux_virgin_copatroness_of_france`.

File: lib/locales/es.ts (hunk 2 above)
Comment (tukusejssirs) [reply lib/locales/es.ts]: Thanks!

**Comment by gtortone** [comment]
Hi, i prefer Aurèlia because accent goes on the third-last vowel and not on the second-last (default). Regarding arbogast_of_strassburg_bishop it seems that Arbogasto is most widespread in Italy (according to Martirologio Romano: https://liturgico.chiesacattolica.it/wp-content/uploads/sites/8/2017/09/21/Martirologio-Romano.pdf - page 564)

**Comment by tukusejssirs** [comment]
> Hi, i prefer Aurèlia because accent goes on the third-last vowel and not on the second-last (default). Regarding arbogast_of_strassburg_bishop it seems that Arbogasto is most widespread in Italy (according to Martirologio Romano: https://liturgico.chiesacattolica.it/wp-content/uploads/sites/8/2017/09/21/Martirologio-Romano.pdf - page 564)

Okay, thanks, @gtortone! I’ll fix the spelling of `Aurèlia` in the next commit. :wink:

File: lib/locales/it.ts [hunk 3]
```diff
@@ -408,23 +397,43 @@ export const locale: Locale = {
...
+    amandus_of_strasbourg_bishop: 'Sant’Amando di Strasburgo, vescovo',
+    aurelia_of_strasbourg_virgin: 'Sant’Aurèlia di Strasburgo, vergine',
+    benedict_of_aniane_abbot: 'San Benedetto d’Aniane, abate',
+    blessed_martyrs_of_paris: 'Beati Martiri della Rivoluzione francese',
+    brigid_of_kildare_virgin: 'Saint Brigida di Kildare, badessa',
+    brigid_of_kildare_virgin_copatroness_of_ireland: 'Saint Brigida di Kildare, badessa e and patrona secondaria d’Irlanda',
+    carmelites_of_compiegne_virgins_and_martyrs: 'Beati carmelitani di Compiègne, vergini e martiri',
+    catherine_zoe_laboure_virgin: 'Santa Caterina Labourè, vergine',
+    ceraunus_of_paris_bishop: 'San Cerauno di Parigi, vescovo',
+    charles_of_jesus_de_foucauld: 'Beato Carlo de Foucauld, sacerdote',
```
Comment (tukusejssirs) [inline lib/locales/it.ts]: @gtortone, what is more used in Italian: `Carlo de Foucauld` or `Carlo di Gesù`?

Comment (gtortone) [reply lib/locales/it.ts]: in Italy it "Charles de Foucauld" is very common... there are a lot of non-profit associations with this name... I've never heard "Carlo de Foucauld"

Comment (tukusejssirs) [reply lib/locales/it.ts]: Okay, I’ve just found [this website](https://www.charlesdefoucauld.it/en/?start=10). I’ll change his name back to `Charles`. Thanks! :pray:

**Comment by HenriqueDerosa** [comment]
Hey @tukusejssirs , really sorry for the delay answering. 😅  🙈 
>  denis_of_paris_bishop_and_companions_martyrs, denis_of_paris_bishop_patron_of_the_archdiocese_of_paris, and denis_of_paris_bishop_patron_of_the_diocese_of_saint_denis: should his name be Dinis or Dionísio?

Any of them: **Dinis** or **Dionísio**. Most of the articles, though, name him **`São Dênis`**. So I believe last option is better.
```
Dênis de Paris, bispo e companheiros mártires,
Dênis de Paris, bispo patrono da arquidiocese de Paris,
Dênis de Paris, buspo patrono da diocese de São Dênis
```
respectively.

**Review by HenriqueDerosa — DISMISSED** [review]
Dionísio is one of the most used. 
I think for this saint it would vary from regions, every content on the web uses all the possible names.

**Comment by tukusejssirs** [comment]
> Hey @tukusejssirs , really sorry for the delay answering. :sweat_smile: :see_no_evil:

No harm done. :wink: I still have too much of work to do within this issue, but my actual work TODO list is even much longer.

> Any of them: Dinis or Dionísio. Most of the articles, though, name him São Dênis. So I believe last option is better.

[This article](https://www.vercalendario.info/pt/evento/liturgia-catolica-9-outubro-2021.html) says its actually _São Denis de Paris e companheiros, mártires_. As this saint is celebration in the GRC, could you double-check it with a Portuguese Roman Missal please? :pray: And if you are at it, could you take pictures of the calendar printed at the beginning of the book (at about pages 82-92; one page per month)? It would be most welcome! :wink:

**Comment by tukusejssirs** [comment]
It’s time to move this PR out of WIP state! :wink:

@emagnier, @gtortone, @CodingAleCR, @jarosz, it’s about to review the changes and to test it out.

@emagnier, there is a lot of changes. You can read through the change list in the PR description. romcal builds without issues, all tests pass (albeit we still lack many tests; I hope I haven’t broke anything). Also I have some questions in [this comment above](https://github.com/romcal/romcal/pull/350#issuecomment-1003771324).

@gtortone, @CodingAleCR, @jarosz, @HenriqueDerosa: in order to ease your localisation review, I have created a list of all changed keys in [this comment above](https://github.com/romcal/romcal/pull/350#issuecomment-1003771324), along with some questions. Take your time to review the changes, however, keep us posted please! :wink:

---

These subissues of #295 are moved to separate issues:

- points 4 and 11 are moved to #369;
- point 7 is moved to #370;
- point 8 is moved to #232;
- point 10 (d) is moved to #371;
- point 10 (i) is moved to #297;
- point 13 is moved to #136.

**Comment by gtortone** [comment]
Hi,
I fixed some untranslated words:

```
brigid_of_kildare_virgin_copatroness_of_ireland
   Santa Brigida di Kildare, badessa e patrona secondaria d’Irlanda

brigid_of_kildare_virgin
   Santa Brigida di Kildare, badessa

eugenia_of_alsace_and_attala_of_alsace_virgins
   Santa Eugènia e Attala, vergini
```

Regarding ```mary_of_the_sacred_heart_sophie_therese_de_soubiran_la_louviere_virgin``` I did not find any
referenco with Sophie Therese De Soubiran La Louviere and Sacred Heart... but it is possible I'm missing something;

Thanks !

**Comment by tukusejssirs** [comment]
> ```
> brigid_of_kildare_virgin_copatroness_of_ireland
>    Santa Brigida di Kildare, badessa e patrona secondaria d’Irlanda
> 
> brigid_of_kildare_virgin
>    Santa Brigida di Kildare, badessa
> ```

These will be fixed in the next commit. Thanks! :pray:

> ```
> eugenia_of_alsace_and_attala_of_alsace_virgins
>    Santa Eugènia e Attala, vergini
> ```

I am not sure if this is correct. You changed `Santas` to `Santa`; why? This celebration contains two saints. Should it be `Santas` or rather `Santi`?

> Regarding `mary_of_the_sacred_heart_sophie_therese_de_soubiran_la_louviere_virgin` I did not find any referenco with Sophie Therese De Soubiran La Louviere and Sacred Heart... but it is possible I'm missing something;

Well, `Mary of the Sacred Heart` is her religious name, `Sophie-Thérèse` is her first name and `de Soubiran La Louvière` is her surname. Depending on the context, she is either described as `[Sister] Mary of the Sacred Heart de Soubiran La Louvière` (religious name and surname; or simply `[Sister] Mary de Soubiran La Louvière`) or `Sophie-Thérèse de Soubiran La Louvière` (first name and surname). Sometimes (or more usually?), her religious name is combined with her first name: `[Sister] Mary Thérèse La Louvière`  or `Sophie-Thérèse de Soubiran La Louvière`. Here are some links:
- [English Wikipedia](https://en.wikipedia.org/wiki/Sophie-Th%C3%A9r%C3%A8se_de_Soubiran_La_Louvi%C3%A8re);
- [Italian Wikipedia](https://it.wikipedia.org/wiki/Maria_Teresa_de_Soubiran_La_Louvi%C3%A8re).

You might be right in one thing: she is not usually called with her ‘full name’. I might change it according to French `Bienheureuse Marie-Thérèse de Soubiran, vierge` to all languages, that is:

- `cs`: `Bl. Marie Terezy de Soubiran La Louvière, panny`;
- `en`: `Blessed Mary Thérèse de Soubiran La Louvière, Virgin`;
- `es`: `Beata María Teresa de Soubiran La Louvière, Vírgen`;
- `it`: `Beata Maria Teresa de Soubiran La Louvière, vergine`;
- `la`: `B. Mariæ Teresiæ de Soubiran La Louvière, virginis`;
- `pl`: `Bł. Marii Teresy de Soubiran La Louvière, dziewicy`;
- `pt-br`: `Beata Maria Teresa de Soubiran La Louvière, virgem`;
- `sk`: `Blahoslavenej Márie Terezy de Soubiran La Louvière, panny`.

I won’t change the key name, as this way it is unique for potential name clashes (like with St Teresia of Jesus).

---

@gortone, so to summarise, here are some tasks you could do for us:
- `eugenia_of_alsace_and_attala_of_alsace_virgins`: This celebration contains two saints. Should we use be `Santas` or rather `Santi`?
- `mary_of_the_sacred_heart_sophie_therese_de_soubiran_la_louviere_virgin`: Is `Beata Maria Teresa de Soubiran La Louvière, vergine` correctly translated?
- Don’t forget to check my questions in [this comment](https://github.com/romcal/romcal/pull/350#issuecomment-1003771324) please.

**Comment by gtortone** [comment]
@tukusejssirs : regarding ```eugenia_of_alsace_and_attala_of_alsace_virgins``` I did not find any reference on Martirologio Romano... so Eugenia is female for sure... if Attala is male (as I think) then 'Santi' else if Attala is female
then 'Sante';

```Beata Maria Teresa de Soubiran La Louvière, vergine``` is correct;

**Comment by gtortone** [comment]
@tukusejssirs 

```eligius_of_noyon_bishop```: Sant’Eligio di Noyon, vescovo

 ```mary_of_the_providence_eugenie_smet_virgin```: I used Eugènia (for the same reason as Aurèlia), however, on [Wiki](https://it.wikipedia.org/wiki/Eug%C3%A9nie_Smet), they write it as Eugenia : in italian 'by default' the accent is on the last syllable then 'Eugenia' without graphic accent must be pronounced as 'Eugenìa'. in this case is not correct then the correct  write is 'Eugénia' as Wikipedia;

```rosalie_jeanne_marie_rendu_virgin```: Rosalia or Rosàlia?... the correct pronounce is Rosalìa but in this case you can write as 'Rosalia' for the rule of 'default' accent on the last syllable...

```translation_of_the_relics_of_odile_of_alsace_abbess```: Odilia or Odìlia or Otilia or Otîlia?  Odìlia  as reported also by Treccani italian encyclopedia (https://www.treccani.it/enciclopedia/santa-odilia/)

 is plural of abate (Abbot) abati? yes, 'abati' is plural of 'abate'

**Comment by tukusejssirs** [comment]
> @tukusejssirs : regarding `eugenia_of_alsace_and_attala_of_alsace_virgins` I did not find any reference on Martirologio Romano... so Eugenia is female for sure... if Attala is male (as I think) then 'Santi' else if Attala is female then 'Sante';

Both Saint Eugenia and Saint Attala are _virgins_, thus they both are female. :wink:

I’ll change `Santas` to `Sante` then, thanks! :pray:

I have no idea why I chose `Santas` in the first place. Now I see that Saint Perpetua and Felicity is translated as `Sante Perpetua e Felicita` in Italian. :facepalm:

Thanks! :pray: This will be fixed in the next commit.

> `Beata Maria Teresa de Soubiran La Louvière, vergine` is correct;

Thanks! :pray:

> `eligius_of_noyon_bishop`: Sant’Eligio di Noyon, vescovo

Okay, then I add `di Noyon` to the Italian key value. That is your intention? Or did you only wanted to say to use `Eligio` instead of `Alo`/`Alò`/`Lo`?

> `mary_of_the_providence_eugenie_smet_virgin`: I used Eugènia (for the same reason as Aurèlia), however, on [Wiki](https://it.wikipedia.org/wiki/Eug%C3%A9nie_Smet), they write it as Eugenia : in italian 'by default' the accent is on the last syllable then 'Eugenia' without graphic accent must be pronounced as 'Eugenìa'. in this case is not correct then the correct write is 'Eugénia' as Wikipedia;

Okay, I’ll keep it as `Eugènia`.

> `rosalie_jeanne_marie_rendu_virgin`: Rosalia or Rosàlia?... the correct pronounce is Rosalìa but in this case you can write as 'Rosalia' for the rule of 'default' accent on the last syllable...

I’m a bit confused. What do you suggest? Is `Rosalia` pronounced in Italian as `Rosalìa`? I’ve thought it is pronounced as `Rosàlia`, therefore I asked you about adding the grave accent or not.

> `translation_of_the_relics_of_odile_of_alsace_abbess`: Odilia or Odìlia or Otilia or Otîlia? Odìlia as reported also by Treccani italian encyclopedia (https://www.treccani.it/enciclopedia/santa-odilia/)

Thanks! :pray: This will be fixed in the next commit.

> is plural of abate (Abbot) abati? yes, 'abati' is plural of 'abate'

Thanks! :pray:

---

Recap: my remaining questions:

- `eligius_of_noyon_bishop`: should I add `di Noyon`?
- `rosalie_jeanne_marie_rendu_virgin`: do you suggest to use `Rosàlia` or `Rosalia`?

**Comment by gtortone** [comment]
@tukusejssirs:

- yes, you can add 'di Noyon'
- i suggest ```Rosalia``` (that for the default accent rule is the same of ```Rosalìa```)

**Comment by emagnier** [comment]
@tukusejssirs: thank you for this massive work of reviewing & polishing the translations, and all keys/calendar definitions!! Here are my answers for the French part:

> `blessed_martyrs_of_paris`: are Blessed Martyrs of Paris and Blessed Martyrs of French Revolution two different groups of blesseds or not? What is the best way to translate this string?

In the proper missal of the diocese of Paris, it's written literally from French "Blessed Martyrs of Paris". Paris isn't France, so it's better to keep these 2 identities separated.

The appropriate translation is `Blessed Martyrs of Paris`.

> I suggest to replace `✝` (U+271D) with `†` (U+2020) in `fr.ts.` (currently, we use both glyphs);

:+1:

> use either `siècle` or `s.` in `fr.ts` (currently, we use both of them);

Let's use the abbreviation `s.`.

> some death dates in `fr.ts` are in brackets, other not; can we put them _always_ in brackets?

:+1:

> `brigid_of_kildare_virgin`: I have no idea how to _really_ solve the issue that some particular calendars use different titles for the same person (in this case, in `ireland.ts`, they use `Virgin`, but in `france.strasbourg.ts`, they use `Abbess`). I understand that it is not a big deal in this particular case, because these two calendars use different keys, but in other cases it is a bit bigger deal. I see only one way to solve this truly is to fix #201 and #232;

Here I don't have an answer right now. I will take the time to look and think of a better solution. Thanks for the issues you have linked here.

> `dedication_of_the_notre_dame_de_paris_cathedral_paris_france` and `dedication_of_the_cathedral_of_notre_dame_de_strasbourg_france`: should we localise `Notre-Dame de {Paris,Strasbourg}` to `Our Lady of {Paris,Strasbourg}`?

We should translate for `Our Lady of...`

But for Paris, it's very common to see that the original name `Notre-Dame de Paris` is kept (because of the notoriety of this cathedral). In my point of view, we should translate by default to `Our Lady of...`, but make an exception for the Paris Cathedral.

> `denis_of_paris_bishop_patron_of_the_diocese_of_saint_denis`: consider creating two keys for each patronages (one for the city, the other for the diocese);

No, because here if you have a look at the calendar of the diocese of Saint-Denis, it refers to the martyrology key `denis_of_paris_bishop`. 
Here, `denis_of_paris_bishop_patron_of_the_diocese_of_saint_denis` is only a custom l10n key, to be able to specify its localized titles in this specific calendar/diocese.

> `sunday_of_the_word_of_god`: could we add `dimanche` after `ou` word, i.e. `Troisième dimanche du Temps Ordinaire, ou dimanche de la Parole de Dieu`? 

Yes :+1:

And no, for the following sentence: _Or maybe `Dimanche`, as it is another celebration name and therefore might be considered a proper name (of the celebration) in French;_

> [not a question, just an info] `merry_and_saint_droctovee_abbots`: according to [[Wiki] _Église Saint-Merri_](https://fr.wikipedia.org/wiki/%C3%89glise_Saint-Merri), Merry/Merri is a contracted name from [Saint Mederic](https://en.wikipedia.org/wiki/Mederic_(monk)) ([fr](https://fr.wikipedia.org/wiki/Saint_M%C3%A9d%C3%A9ric)); also, it is quite strange that the celebration name in the French Proper contains the canonisation level twice (once for each saint);

I'm not sure to understand. For example, `philip_and_james_apostles` also contains the canonization level twice (once for each saint). This is more common in French.

However, we should remove the keyword `saint` in this calendar key => `merry_and_droctovee_abbots`

> is this needed in `ireland.ts`, when St Pius celebration is already memorial in the GRC? Can we safely delete it?
```ts
// Ireland
pius_francesco_forgione_priest: {
  precedence: Precedences.GeneralMemorial_10,
  dateDef: { month: 9, date: 23 },
},

// GRC
pius_francesco_forgione_priest: {
  precedence: Precedences.GeneralMemorial_10,
  dateDef: { month: 9, date: 23 },
},
```

Yes, we can safely remove this calendar definition from `ireland.ts`. Especially since these definitions are strictly identical.

**Comment by tukusejssirs** [comment]
Thanks, @emagnier, for reviewing this issue! :pray:

I’ll fix the suggestions you agreed with later this week. :wink:

Below I comment on your comments. I won’t comment on resolved issues.

---

1. Celebrations with different personal titles in different calendars.

> [emagnier] Here I don't have an answer right now. I will take the time to look and think of a better solution. Thanks for the issues you have linked here.

While #201 is partially implemented (we can specify titles within celebration definitions, however, they are not used to generate the celebration title; also, in `lib/catalog/martyrology.ts`, we don’t specify a list of all possible titles that can be used with a particular person) and also #232 (we can localise the titles, however, they are not used to generate the celebration name).

Thus, #154 is the issue that should be fixed: when it is fixed, this issue (celebrations with different personal titles in different calendars) could be easily fixed.

Thus I think that we should concentrate on the following stuff:
- [ ] update the type definition of martyrology, l10n, celebration and calendar objects (#365):
  - this is needed to add some metadata (properties) and update some types;
- [ ] use `i18next-fluent` (#369):
  - IMHO this is needed to make the localisation easier for more complicated languages;
- [ ] split l10n metadata (#154);
- [ ] create a way to generate celebration names from the l10n metadata (#381; related to #241):
  - including function to:
    - generate IDs (keys) of anything (martyrology items, celebration definitions, l10n items, …);
    - generate celebration names from l10n metadata based on the locale configuration.

Anyway, we won’t solve this in this PR. However, I think we should fix this before releasing `v3.0.0`, as I think there are many issues related to this. Also, whenever I go through the list of l10n keys, sometimes make mistakes (like forgetting to localise a title). After this, we could release `v3.0.0`, then we could create some GUI apps (later to be hosted on some website) to manage celebrations, martyrology (and non-personal celebrations) and localisations, which would make it much easier for potential non-technical contributors and could provide some checks to prevent the most common errors.

---

2. Should we use `Notre-Dame` or `Our Lady` in `en.ts` in `dedication_of_the_notre_dame_de_paris_cathedral_paris_france` and `dedication_of_the_cathedral_of_notre_dame_de_strasbourg_france`?

> [emagnier] We should translate for `Our Lady of...` … But for Paris, it's very common to see that the original name `Notre-Dame de Paris` is kept (because of the notoriety of this cathedral). In my point of view, we should translate by default to `Our Lady of...`, but make an exception for the Paris Cathedral.

Well, I agree that Notre-Dame of Paris Cathedral is frequently used with `Notre-Dame` in English too. That might be a reason _for_ keeping it untranslated.

On the other hand, the English Translation of the Roman Missal (2011; ed. typ. tertia), based on the rules Holy See decreed, translated many names and words literally (same is true of the Slovak translation of the RM from 2021).

In the end, if we translate one of the keys, IMHO we should translate all of them. This is actually the reason why I kept `Notre-Dame` untranslated.

Your thoughts based my comments? :wink:

This should be fixed in this issue.

---

3. `denis_of_paris_bishop_patron_of_the_diocese_of_saint_denis`: consider creating two keys for each patronages (one for the city, the other for the diocese; see issue #371).

There are two levels of this issue:

a. localisation:
  - This is what you have picked up.
  - Indeed, this issue is not an issue in this level, as l10n does not depend on neither calendars on celebrations.
  - However, changes to the calendar and/or celebrations might cause changes to the l10n files (which is actually the case in here; see below).

b. calendar:
  - The issue is about suggestion to create two separate celebrations in two calendars:
    - [city calendar]: `Patron of the City and of the Diocese of Saint-Denis`;
    - [diocese calendar]: `Patron of the Diocese of Saint-Denis`.
  - I understand that the diocesan Calendar Proper lists only `Patron of the City and of the Diocese of Saint-Denis`, however, semantically, it does not makes sense, as `Patron of the City [of Saint-Denis]` is never celebrated outside of the city. In the Diocese (outside of the City), they celebrate only `Patron of the Diocese of Saint-Denis`.
  - Actually, I have the same issue in the Slovak dioceses (as I am in the middle of adding their calendars into romcal).
  - Tracking issue: #371.
  - Related issue: #376.

This could be fixed in this issue or it could be moved to separate one.

---

4. Adding `dimanche` to `sunday_of_the_word_of_god` in `fr.ts`.

You agree with this, however you disagree with adding `Dimanche` (with capital `D`).

I think that `Troisième dimanche du Temps Ordinaire` and `Dimanche de la Parole de Dieu` are two separate titles (celebration names). I presume that even in French a heading (e.g. used in the sentence context) is to be written same way as you would write then as titles/headings of an article/book/whatever.

Do you still disagree? Are my presumptions invalid? :wink:

This should be fixed in this issue.

---

5. Use `Saints` or `Saint` multiple times in a single key in `fr.ts`? (e.g. `mederic_of_autun_and_droctoveus_of_autun_abbots`).

> [@emagnier] [Using `Saint` multiple times] is more common in French.

Okay, this is more of a style issue. I have no problem with using `Saint` (or `Blessed`) multiple times within a single key as long as it is done consistently.

I have some some time today to check if this is used consistently in `fr.ts`, only to find out that there are many issues in the 34 keys that contain `Saints`/`Blesseds` in `en.ts` (for more information, see [this comment](https://github.com/romcal/romcal/issues/256#issuecomment-1265925764) in #256). Therefore I decided I won’t solve this in this issue. I invite you to comment on this in that issue.

---

6. Put death dates always in brackets.

While you agreed with my suggestion, while looking at various (French) Propers you shared with me, there are some propers that use brackets, does separate the death dates with commas, some don’t even mention the death dates (see [this comment](https://github.com/romcal/romcal/issues/256#issuecomment-1265925764) in #256).

I think for now in order to make it consistent, we should put the death dates in brackets, however, later we should add a locale config option to choose how (if at all) should we style the celebration name.

**Comment by emagnier** [comment]
Thanks @tukusejssirs! A few comments:

2. Not very sure to understand your conclusion, but yes, translate all the keys, except the ones that are well-known with their original name (like Notre-Dame of Paris).
3. I agree that the patron of the city do not really make sense here. I just translated literally what is written in the proper missal. Feel free to adjust this in any way you think is best.
4. In French, week day names are written lowercase in a sentence (unlike English). And `Troisième dimanche du Temps Ordinaire` and `Dimanche de la Parole de Dieu` are in fact the same liturgical day (same readings, same prayers, same celebration...), but might be considered as a title + a subtitle. It's like the Divine Mercy Sunday. And in this 2 Sundays, the `dimanche` word was not rewritten in the French-speaking missal, surely to avoid repetitions.
5. 👍 
6. 👍

**Comment by tukusejssirs** [comment]
> 2. Not very sure to understand your conclusion, but yes, translate all the keys, except the ones that are well-known with their original name (like Notre-Dame of Paris).

If you agree with me, let’s keep both Notre-Dames in the original.

> 3. I agree that the patron of the city do not really make sense here. I just translated literally what is written in the proper missal. Feel free to adjust this in any way you think is best.

We’ll deal with this in #371.

> 4. In French, week day names are written lowercase in a sentence (unlike English). And `Troisième dimanche du Temps Ordinaire` and `Dimanche de la Parole de Dieu` are in fact the same liturgical day (same readings, same prayers, same celebration...), but might be considered as a title + a subtitle. It's like the Divine Mercy Sunday. And in this 2 Sundays, the `dimanche` word was not rewritten in the French-speaking missal, surely to avoid repetitions.

Well, in Slovak (similarly to French), we use sentence case for title case, i.e all titles/heading are in sentence case; only _**first word**_ and proper nouns/words have initial uppercase letter.

IMHO `Troisième dimanche du Temps Ordinaire` is title (celebration name) and `Dimanche de la Parole de Dieu` is subtitle. However, subtitle follows same rules as title: they both use title case (or sentence case based on the locale). Thus both title and subtitle should start with uppercase initial letter. Same rules should apply to all celebrations with a subtitle (see [#297 issue description](https://github.com/romcal/romcal/issues/297)), thus also for the Sunday of Divine Mercy.

> `Troisième dimanche du Temps Ordinaire` and `Dimanche de la Parole de Dieu` are in fact the same liturgical day (same readings, same prayers, same celebration...)

We are talking about l10n, not about celebration definition / calendars. Indeed, the liturgical rules are exactly the same, as it is the same celebration, but different name. :wink:

> the `dimanche` word was not rewritten in the French-speaking missal, surely to avoid repetitions.

Well, from one point it makes some, from another one it sound a bit noisy (at least when reading it). Another point for using two `dimanche` words is the consistently and making it easier to use in code. However, for now either one it good enough, however when #297 is implemented, we definitely will use two `dimanche` words.

If you agree with me, let’s use `Troisième dimanche du Temps Ordinaire, ou Dimanche de la Parole de Dieu` at treat it as `${title}, ou ${subtitle}`.

**Comment by tukusejssirs** [comment]
@emagnier, I’ve made the following changes:

- `fr.ts`:
   - replace `✝` (`U+271D`) with `†` (`U+2020`);
   - add missing `†` before death dates;
   - replace `siècle` with `s.`;
   - put death dates always in brackets;
   - `sunday_of_the_word_of_god`: add `Dimanche` after `ou` word, i.e. `Troisième dimanche du Temps Ordinaire, ou Dimanche de la Parole de Dieu`;
- `ireland.ts`: remove `pius_francesco_forgione_priest`, as it is already defined in the GRC.

**Review by emagnier — DISMISSED** [review]
Agreed with your 2 last comments 👍 

Feel free to merge this PR when you think it's ready, or create separated PR/issues for the remaining points.

**Comment by tukusejssirs** [comment]
Well, from my point of view, I did my best, thus it is ready. However, I raised some l10n issues which needs to be fixed/verified by native speakers.

@CodingAleCR, @jarosz, @HenriqueDerosa, final call to review this PR. Could you help us by answering questions raised in [this comment](https://github.com/romcal/romcal/pull/350#issuecomment-1003771324) please? Unless you react (even with a comment like _wait please_), I’ll merge this on 10 October 2022. Thanks! :pray:

**Comment by tukusejssirs** [comment]
@emagnier, we can merge this PR. I moved the (potential) l10n issues into separate issues (based on the locale):
- `pl.ts`: #278;
- `pt-br.ts`: #387;
- `es.ts`: #388.

**Review by emagnier — APPROVED** [review]

**Comment by tukusejssirs** [comment]
@emagnier, thanks for approving the PR! :pray:

However, tag `v3.0.0-dev.11` already exists (99f5ae2c), thus the publish job fails; see the [logs](https://github.com/romcal/romcal/actions/runs/3243112029/jobs/5317350712#step:11:28).

For some reason, in my local copy of (upstream) romcal repository, the lateset tag is `v3.0.0-dev.18` (7caed050), however, on GitHub, the latest is `v3.0.0-dev.11`. It looks like you have removed some tags I have previously pulled. I have no problem to remove my local tags, however, the next version must be `v3.0.0-dev.12` (even on NPM, the latest version is [`v3.0.0-dev.11`](https://www.npmjs.com/package/romcal)).

_Automated version bump_ (see [logs](https://github.com/romcal/romcal/actions/runs/3243112029/jobs/5317350712#step:4:30)) failed to bump the version, as we need to add a version _wording_ (`major`/`minor`/`patch`). It is okay for stable releases and for `dev` releases, when a change in a commit triggers a `minor` or `major` version incremention, however, by default, IMHO it should be set to `minor` for `dev` versions. For stable releases, a requirement to set an increment type should be mandatory IMHO.
